// AUTO-GENERATED from config/market_catalog_ux_test.json by scripts/gen_market_catalog.mjs.
// DO NOT EDIT BY HAND. Run `node scripts/gen_market_catalog.mjs` after editing the JSON.
//
// DISPLAY-ONLY catalogue (MKT-1 test UX). NOT the product perimeter: the engine
// follows config/markets.json alone. A market listed here and absent from the real
// registry has NO data behind it — see lib/market-catalog.ts.
export type CatalogGroup = 'fx-major' | 'fx-minor' | 'fx-exotic' | 'metal' | 'index' | 'crypto';

export const CATALOG_GROUPS: readonly CatalogGroup[] = ['fx-major', 'fx-minor', 'fx-exotic', 'metal', 'index', 'crypto'];

export interface CatalogEntry {
  id: string;
  label: string;
  symbol: string;
  group: CatalogGroup;
  glyph: string;
  index: number;
}

export const CATALOG_ENTRIES: readonly CatalogEntry[] = [
  { id: "EURUSD", label: "Euro / Dollar (EUR/USD)", symbol: "EURUSD", group: "fx-major", glyph: "€", index: 0 },
  { id: "GBPUSD", label: "Livre / Dollar (GBP/USD)", symbol: "GBPUSD", group: "fx-major", glyph: "£", index: 1 },
  { id: "USDJPY", label: "Dollar / Yen (USD/JPY)", symbol: "USDJPY", group: "fx-major", glyph: "$", index: 2 },
  { id: "USDCHF", label: "Dollar / Franc suisse (USD/CHF)", symbol: "USDCHF", group: "fx-major", glyph: "$", index: 3 },
  { id: "USDCAD", label: "Dollar / Dollar canadien (USD/CAD)", symbol: "USDCAD", group: "fx-major", glyph: "$", index: 4 },
  { id: "AUDUSD", label: "Dollar australien / Dollar (AUD/USD)", symbol: "AUDUSD", group: "fx-major", glyph: "A$", index: 5 },
  { id: "NZDUSD", label: "Dollar néo-zélandais / Dollar (NZD/USD)", symbol: "NZDUSD", group: "fx-major", glyph: "N$", index: 6 },
  { id: "EURGBP", label: "Euro / Livre (EUR/GBP)", symbol: "EURGBP", group: "fx-minor", glyph: "€", index: 7 },
  { id: "EURJPY", label: "Euro / Yen (EUR/JPY)", symbol: "EURJPY", group: "fx-minor", glyph: "€", index: 8 },
  { id: "EURCHF", label: "Euro / Franc suisse (EUR/CHF)", symbol: "EURCHF", group: "fx-minor", glyph: "€", index: 9 },
  { id: "EURAUD", label: "Euro / Dollar australien (EUR/AUD)", symbol: "EURAUD", group: "fx-minor", glyph: "€", index: 10 },
  { id: "EURCAD", label: "Euro / Dollar canadien (EUR/CAD)", symbol: "EURCAD", group: "fx-minor", glyph: "€", index: 11 },
  { id: "EURNZD", label: "Euro / Dollar néo-zélandais (EUR/NZD)", symbol: "EURNZD", group: "fx-minor", glyph: "€", index: 12 },
  { id: "GBPJPY", label: "Livre / Yen (GBP/JPY)", symbol: "GBPJPY", group: "fx-minor", glyph: "£", index: 13 },
  { id: "GBPCHF", label: "Livre / Franc suisse (GBP/CHF)", symbol: "GBPCHF", group: "fx-minor", glyph: "£", index: 14 },
  { id: "GBPAUD", label: "Livre / Dollar australien (GBP/AUD)", symbol: "GBPAUD", group: "fx-minor", glyph: "£", index: 15 },
  { id: "GBPCAD", label: "Livre / Dollar canadien (GBP/CAD)", symbol: "GBPCAD", group: "fx-minor", glyph: "£", index: 16 },
  { id: "GBPNZD", label: "Livre / Dollar néo-zélandais (GBP/NZD)", symbol: "GBPNZD", group: "fx-minor", glyph: "£", index: 17 },
  { id: "AUDJPY", label: "Dollar australien / Yen (AUD/JPY)", symbol: "AUDJPY", group: "fx-minor", glyph: "A$", index: 18 },
  { id: "AUDCHF", label: "Dollar australien / Franc suisse (AUD/CHF)", symbol: "AUDCHF", group: "fx-minor", glyph: "A$", index: 19 },
  { id: "AUDCAD", label: "Dollar australien / Dollar canadien (AUD/CAD)", symbol: "AUDCAD", group: "fx-minor", glyph: "A$", index: 20 },
  { id: "AUDNZD", label: "Dollar australien / Dollar néo-zélandais (AUD/NZD)", symbol: "AUDNZD", group: "fx-minor", glyph: "A$", index: 21 },
  { id: "CADJPY", label: "Dollar canadien / Yen (CAD/JPY)", symbol: "CADJPY", group: "fx-minor", glyph: "C$", index: 22 },
  { id: "CADCHF", label: "Dollar canadien / Franc suisse (CAD/CHF)", symbol: "CADCHF", group: "fx-minor", glyph: "C$", index: 23 },
  { id: "CHFJPY", label: "Franc suisse / Yen (CHF/JPY)", symbol: "CHFJPY", group: "fx-minor", glyph: "₣", index: 24 },
  { id: "NZDJPY", label: "Dollar néo-zélandais / Yen (NZD/JPY)", symbol: "NZDJPY", group: "fx-minor", glyph: "N$", index: 25 },
  { id: "NZDCHF", label: "Dollar néo-zélandais / Franc suisse (NZD/CHF)", symbol: "NZDCHF", group: "fx-minor", glyph: "N$", index: 26 },
  { id: "NZDCAD", label: "Dollar néo-zélandais / Dollar canadien (NZD/CAD)", symbol: "NZDCAD", group: "fx-minor", glyph: "N$", index: 27 },
  { id: "USDTRY", label: "Dollar / Livre turque (USD/TRY)", symbol: "USDTRY", group: "fx-exotic", glyph: "$", index: 28 },
  { id: "USDZAR", label: "Dollar / Rand (USD/ZAR)", symbol: "USDZAR", group: "fx-exotic", glyph: "$", index: 29 },
  { id: "USDMXN", label: "Dollar / Peso mexicain (USD/MXN)", symbol: "USDMXN", group: "fx-exotic", glyph: "$", index: 30 },
  { id: "USDSEK", label: "Dollar / Couronne suédoise (USD/SEK)", symbol: "USDSEK", group: "fx-exotic", glyph: "$", index: 31 },
  { id: "USDNOK", label: "Dollar / Couronne norvégienne (USD/NOK)", symbol: "USDNOK", group: "fx-exotic", glyph: "$", index: 32 },
  { id: "USDDKK", label: "Dollar / Couronne danoise (USD/DKK)", symbol: "USDDKK", group: "fx-exotic", glyph: "$", index: 33 },
  { id: "USDPLN", label: "Dollar / Zloty (USD/PLN)", symbol: "USDPLN", group: "fx-exotic", glyph: "$", index: 34 },
  { id: "USDHUF", label: "Dollar / Forint (USD/HUF)", symbol: "USDHUF", group: "fx-exotic", glyph: "$", index: 35 },
  { id: "USDCZK", label: "Dollar / Couronne tchèque (USD/CZK)", symbol: "USDCZK", group: "fx-exotic", glyph: "$", index: 36 },
  { id: "USDSGD", label: "Dollar / Dollar de Singapour (USD/SGD)", symbol: "USDSGD", group: "fx-exotic", glyph: "$", index: 37 },
  { id: "USDHKD", label: "Dollar / Dollar de Hong Kong (USD/HKD)", symbol: "USDHKD", group: "fx-exotic", glyph: "$", index: 38 },
  { id: "USDTHB", label: "Dollar / Baht (USD/THB)", symbol: "USDTHB", group: "fx-exotic", glyph: "$", index: 39 },
  { id: "USDCNH", label: "Dollar / Yuan offshore (USD/CNH)", symbol: "USDCNH", group: "fx-exotic", glyph: "$", index: 40 },
  { id: "USDINR", label: "Dollar / Roupie indienne (USD/INR)", symbol: "USDINR", group: "fx-exotic", glyph: "$", index: 41 },
  { id: "USDBRL", label: "Dollar / Réal (USD/BRL)", symbol: "USDBRL", group: "fx-exotic", glyph: "$", index: 42 },
  { id: "EURTRY", label: "Euro / Livre turque (EUR/TRY)", symbol: "EURTRY", group: "fx-exotic", glyph: "€", index: 43 },
  { id: "EURZAR", label: "Euro / Rand (EUR/ZAR)", symbol: "EURZAR", group: "fx-exotic", glyph: "€", index: 44 },
  { id: "EURPLN", label: "Euro / Zloty (EUR/PLN)", symbol: "EURPLN", group: "fx-exotic", glyph: "€", index: 45 },
  { id: "EURSEK", label: "Euro / Couronne suédoise (EUR/SEK)", symbol: "EURSEK", group: "fx-exotic", glyph: "€", index: 46 },
  { id: "EURNOK", label: "Euro / Couronne norvégienne (EUR/NOK)", symbol: "EURNOK", group: "fx-exotic", glyph: "€", index: 47 },
  { id: "XAUUSD", label: "Or (XAU/USD)", symbol: "XAUUSD", group: "metal", glyph: "Au", index: 48 },
  { id: "XAGUSD", label: "Argent (XAG/USD)", symbol: "XAGUSD", group: "metal", glyph: "Ag", index: 49 },
  { id: "XPTUSD", label: "Platine (XPT/USD)", symbol: "XPTUSD", group: "metal", glyph: "Pt", index: 50 },
  { id: "XPDUSD", label: "Palladium (XPD/USD)", symbol: "XPDUSD", group: "metal", glyph: "Pd", index: 51 },
  { id: "XAUEUR", label: "Or en euro (XAU/EUR)", symbol: "XAUEUR", group: "metal", glyph: "Au", index: 52 },
  { id: "XAGEUR", label: "Argent en euro (XAG/EUR)", symbol: "XAGEUR", group: "metal", glyph: "Ag", index: 53 },
  { id: "XAUGBP", label: "Or en livre (XAU/GBP)", symbol: "XAUGBP", group: "metal", glyph: "Au", index: 54 },
  { id: "XAUJPY", label: "Or en yen (XAU/JPY)", symbol: "XAUJPY", group: "metal", glyph: "Au", index: 55 },
  { id: "US500", label: "S&P 500 (États-Unis)", symbol: "US500", group: "index", glyph: "US", index: 56 },
  { id: "US30", label: "Dow Jones 30 (États-Unis)", symbol: "US30", group: "index", glyph: "DJ", index: 57 },
  { id: "NAS100", label: "Nasdaq 100 (États-Unis)", symbol: "NAS100", group: "index", glyph: "NQ", index: 58 },
  { id: "US2000", label: "Russell 2000 (États-Unis)", symbol: "US2000", group: "index", glyph: "RU", index: 59 },
  { id: "GER40", label: "DAX 40 (Allemagne)", symbol: "GER40", group: "index", glyph: "DE", index: 60 },
  { id: "UK100", label: "FTSE 100 (Royaume-Uni)", symbol: "UK100", group: "index", glyph: "UK", index: 61 },
  { id: "FRA40", label: "CAC 40 (France)", symbol: "FRA40", group: "index", glyph: "FR", index: 62 },
  { id: "EU50", label: "Euro Stoxx 50 (zone euro)", symbol: "EU50", group: "index", glyph: "EU", index: 63 },
  { id: "ESP35", label: "IBEX 35 (Espagne)", symbol: "ESP35", group: "index", glyph: "ES", index: 64 },
  { id: "ITA40", label: "FTSE MIB (Italie)", symbol: "ITA40", group: "index", glyph: "IT", index: 65 },
  { id: "SUI20", label: "SMI 20 (Suisse)", symbol: "SUI20", group: "index", glyph: "CH", index: 66 },
  { id: "NED25", label: "AEX 25 (Pays-Bas)", symbol: "NED25", group: "index", glyph: "NL", index: 67 },
  { id: "JP225", label: "Nikkei 225 (Japon)", symbol: "JP225", group: "index", glyph: "JP", index: 68 },
  { id: "HK50", label: "Hang Seng (Hong Kong)", symbol: "HK50", group: "index", glyph: "HK", index: 69 },
  { id: "AUS200", label: "ASX 200 (Australie)", symbol: "AUS200", group: "index", glyph: "AU", index: 70 },
  { id: "CHN50", label: "China A50 (Chine)", symbol: "CHN50", group: "index", glyph: "CN", index: 71 },
  { id: "IND50", label: "Nifty 50 (Inde)", symbol: "IND50", group: "index", glyph: "IN", index: 72 },
  { id: "CAN60", label: "TSX 60 (Canada)", symbol: "CAN60", group: "index", glyph: "CA", index: 73 },
  { id: "VIX", label: "Indice de volatilité VIX", symbol: "VIX", group: "index", glyph: "VX", index: 74 },
  { id: "USDX", label: "Indice dollar (DXY)", symbol: "USDX", group: "index", glyph: "DX", index: 75 },
  { id: "BTCUSD", label: "Bitcoin (BTC/USD)", symbol: "BTCUSD", group: "crypto", glyph: "₿", index: 76 },
  { id: "ETHUSD", label: "Ethereum (ETH/USD)", symbol: "ETHUSD", group: "crypto", glyph: "Ξ", index: 77 },
  { id: "XRPUSD", label: "XRP (XRP/USD)", symbol: "XRPUSD", group: "crypto", glyph: "XR", index: 78 },
  { id: "LTCUSD", label: "Litecoin (LTC/USD)", symbol: "LTCUSD", group: "crypto", glyph: "LT", index: 79 },
  { id: "BCHUSD", label: "Bitcoin Cash (BCH/USD)", symbol: "BCHUSD", group: "crypto", glyph: "BC", index: 80 },
  { id: "ADAUSD", label: "Cardano (ADA/USD)", symbol: "ADAUSD", group: "crypto", glyph: "AD", index: 81 },
  { id: "SOLUSD", label: "Solana (SOL/USD)", symbol: "SOLUSD", group: "crypto", glyph: "SO", index: 82 },
  { id: "DOTUSD", label: "Polkadot (DOT/USD)", symbol: "DOTUSD", group: "crypto", glyph: "DO", index: 83 },
  { id: "DOGEUSD", label: "Dogecoin (DOGE/USD)", symbol: "DOGEUSD", group: "crypto", glyph: "DG", index: 84 },
  { id: "LINKUSD", label: "Chainlink (LINK/USD)", symbol: "LINKUSD", group: "crypto", glyph: "LK", index: 85 },
  { id: "AVAXUSD", label: "Avalanche (AVAX/USD)", symbol: "AVAXUSD", group: "crypto", glyph: "AV", index: 86 },
  { id: "MATICUSD", label: "Polygon (MATIC/USD)", symbol: "MATICUSD", group: "crypto", glyph: "MA", index: 87 },
  { id: "BNBUSD", label: "BNB (BNB/USD)", symbol: "BNBUSD", group: "crypto", glyph: "BN", index: 88 },
  { id: "TRXUSD", label: "TRON (TRX/USD)", symbol: "TRXUSD", group: "crypto", glyph: "TX", index: 89 },
  { id: "XLMUSD", label: "Stellar (XLM/USD)", symbol: "XLMUSD", group: "crypto", glyph: "XL", index: 90 },
  { id: "ATOMUSD", label: "Cosmos (ATOM/USD)", symbol: "ATOMUSD", group: "crypto", glyph: "AT", index: 91 },
  { id: "UNIUSD", label: "Uniswap (UNI/USD)", symbol: "UNIUSD", group: "crypto", glyph: "UN", index: 92 },
  { id: "ETCUSD", label: "Ethereum Classic (ETC/USD)", symbol: "ETCUSD", group: "crypto", glyph: "EC", index: 93 },
  { id: "FILUSD", label: "Filecoin (FIL/USD)", symbol: "FILUSD", group: "crypto", glyph: "FL", index: 94 },
  { id: "NEARUSD", label: "NEAR Protocol (NEAR/USD)", symbol: "NEARUSD", group: "crypto", glyph: "NR", index: 95 },
  { id: "BTCEUR", label: "Bitcoin en euro (BTC/EUR)", symbol: "BTCEUR", group: "crypto", glyph: "₿", index: 96 },
  { id: "ETHEUR", label: "Ethereum en euro (ETH/EUR)", symbol: "ETHEUR", group: "crypto", glyph: "Ξ", index: 97 },
  { id: "SOLEUR", label: "Solana en euro (SOL/EUR)", symbol: "SOLEUR", group: "crypto", glyph: "SO", index: 98 },
  { id: "BTCGBP", label: "Bitcoin en livre (BTC/GBP)", symbol: "BTCGBP", group: "crypto", glyph: "₿", index: 99 },
];
