// AUTO-GENERATED from config/markets.json by scripts/gen_markets.mjs.
// DO NOT EDIT BY HAND. Run `node scripts/gen_markets.mjs` after editing the JSON.
export type MarketType = 'metal' | 'fx' | 'crypto' | 'index';

export interface MarketSpec {
  id: string;
  label: string;
  symbol: string;
  type: MarketType;
  priceDecimals: number;
  glyph: string;
  timeframes: readonly string[];
  index: number;
}

export const MARKET_SPECS: readonly MarketSpec[] = [
  { id: "XAUUSD", label: "Or (XAU/USD)", symbol: "XAUUSD", type: "metal", priceDecimals: 2, glyph: "Au", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 0 },
  { id: "EURUSD", label: "Euro / Dollar (EUR/USD)", symbol: "EURUSD", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 1 },
  { id: "GBPUSD", label: "Livre / Dollar (GBP/USD)", symbol: "GBPUSD", type: "fx", priceDecimals: 5, glyph: "£", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 2 },
  { id: "USDJPY", label: "Dollar / Yen (USD/JPY)", symbol: "USDJPY", type: "fx", priceDecimals: 3, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 3 },
  { id: "USDCHF", label: "Dollar / Franc suisse (USD/CHF)", symbol: "USDCHF", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 4 },
  { id: "USDCAD", label: "Dollar / Dollar canadien (USD/CAD)", symbol: "USDCAD", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 5 },
  { id: "AUDUSD", label: "Dollar australien / Dollar (AUD/USD)", symbol: "AUDUSD", type: "fx", priceDecimals: 5, glyph: "A$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 6 },
  { id: "NZDUSD", label: "Dollar néo-zélandais / Dollar (NZD/USD)", symbol: "NZDUSD", type: "fx", priceDecimals: 5, glyph: "N$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 7 },
  { id: "EURGBP", label: "Euro / Livre (EUR/GBP)", symbol: "EURGBP", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 8 },
  { id: "EURJPY", label: "Euro / Yen (EUR/JPY)", symbol: "EURJPY", type: "fx", priceDecimals: 3, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 9 },
  { id: "EURCHF", label: "Euro / Franc suisse (EUR/CHF)", symbol: "EURCHF", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 10 },
  { id: "EURAUD", label: "Euro / Dollar australien (EUR/AUD)", symbol: "EURAUD", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 11 },
  { id: "EURCAD", label: "Euro / Dollar canadien (EUR/CAD)", symbol: "EURCAD", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 12 },
  { id: "EURNZD", label: "Euro / Dollar néo-zélandais (EUR/NZD)", symbol: "EURNZD", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 13 },
  { id: "GBPJPY", label: "Livre / Yen (GBP/JPY)", symbol: "GBPJPY", type: "fx", priceDecimals: 3, glyph: "£", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 14 },
  { id: "GBPCHF", label: "Livre / Franc suisse (GBP/CHF)", symbol: "GBPCHF", type: "fx", priceDecimals: 5, glyph: "£", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 15 },
  { id: "GBPAUD", label: "Livre / Dollar australien (GBP/AUD)", symbol: "GBPAUD", type: "fx", priceDecimals: 5, glyph: "£", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 16 },
  { id: "GBPCAD", label: "Livre / Dollar canadien (GBP/CAD)", symbol: "GBPCAD", type: "fx", priceDecimals: 5, glyph: "£", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 17 },
  { id: "GBPNZD", label: "Livre / Dollar néo-zélandais (GBP/NZD)", symbol: "GBPNZD", type: "fx", priceDecimals: 5, glyph: "£", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 18 },
  { id: "AUDJPY", label: "Dollar australien / Yen (AUD/JPY)", symbol: "AUDJPY", type: "fx", priceDecimals: 3, glyph: "A$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 19 },
  { id: "AUDCHF", label: "Dollar australien / Franc suisse (AUD/CHF)", symbol: "AUDCHF", type: "fx", priceDecimals: 5, glyph: "A$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 20 },
  { id: "AUDCAD", label: "Dollar australien / Dollar canadien (AUD/CAD)", symbol: "AUDCAD", type: "fx", priceDecimals: 5, glyph: "A$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 21 },
  { id: "AUDNZD", label: "Dollar australien / Dollar néo-zélandais (AUD/NZD)", symbol: "AUDNZD", type: "fx", priceDecimals: 5, glyph: "A$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 22 },
  { id: "CADJPY", label: "Dollar canadien / Yen (CAD/JPY)", symbol: "CADJPY", type: "fx", priceDecimals: 3, glyph: "C$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 23 },
  { id: "CADCHF", label: "Dollar canadien / Franc suisse (CAD/CHF)", symbol: "CADCHF", type: "fx", priceDecimals: 5, glyph: "C$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 24 },
  { id: "CHFJPY", label: "Franc suisse / Yen (CHF/JPY)", symbol: "CHFJPY", type: "fx", priceDecimals: 3, glyph: "₣", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 25 },
  { id: "NZDJPY", label: "Dollar néo-zélandais / Yen (NZD/JPY)", symbol: "NZDJPY", type: "fx", priceDecimals: 3, glyph: "N$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 26 },
  { id: "NZDCHF", label: "Dollar néo-zélandais / Franc suisse (NZD/CHF)", symbol: "NZDCHF", type: "fx", priceDecimals: 5, glyph: "N$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 27 },
  { id: "NZDCAD", label: "Dollar néo-zélandais / Dollar canadien (NZD/CAD)", symbol: "NZDCAD", type: "fx", priceDecimals: 5, glyph: "N$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 28 },
  { id: "XAGUSD", label: "Argent (XAG/USD)", symbol: "XAGUSD", type: "metal", priceDecimals: 2, glyph: "Ag", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 29 },
  { id: "XPTUSD", label: "Platine (XPT/USD)", symbol: "XPTUSD", type: "metal", priceDecimals: 2, glyph: "Pt", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 30 },
  { id: "XPDUSD", label: "Palladium (XPD/USD)", symbol: "XPDUSD", type: "metal", priceDecimals: 2, glyph: "Pd", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 31 },
  { id: "XAUEUR", label: "Or en euro (XAU/EUR)", symbol: "XAUEUR", type: "metal", priceDecimals: 2, glyph: "Au", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 32 },
  { id: "XAGEUR", label: "Argent en euro (XAG/EUR)", symbol: "XAGEUR", type: "metal", priceDecimals: 2, glyph: "Ag", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 33 },
  { id: "XAUGBP", label: "Or en livre (XAU/GBP)", symbol: "XAUGBP", type: "metal", priceDecimals: 2, glyph: "Au", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 34 },
  { id: "XAUJPY", label: "Or en yen (XAU/JPY)", symbol: "XAUJPY", type: "metal", priceDecimals: 2, glyph: "Au", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 35 },
  { id: "BTCUSD", label: "Bitcoin (BTC/USD)", symbol: "BTCUSD", type: "crypto", priceDecimals: 2, glyph: "₿", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 36 },
  { id: "ETHUSD", label: "Ethereum (ETH/USD)", symbol: "ETHUSD", type: "crypto", priceDecimals: 2, glyph: "Ξ", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 37 },
  { id: "XRPUSD", label: "XRP (XRP/USD)", symbol: "XRPUSD", type: "crypto", priceDecimals: 2, glyph: "XR", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 38 },
  { id: "LTCUSD", label: "Litecoin (LTC/USD)", symbol: "LTCUSD", type: "crypto", priceDecimals: 2, glyph: "LT", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 39 },
  { id: "BCHUSD", label: "Bitcoin Cash (BCH/USD)", symbol: "BCHUSD", type: "crypto", priceDecimals: 2, glyph: "BC", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 40 },
  { id: "ADAUSD", label: "Cardano (ADA/USD)", symbol: "ADAUSD", type: "crypto", priceDecimals: 2, glyph: "AD", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 41 },
  { id: "SOLUSD", label: "Solana (SOL/USD)", symbol: "SOLUSD", type: "crypto", priceDecimals: 2, glyph: "SO", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 42 },
  { id: "DOTUSD", label: "Polkadot (DOT/USD)", symbol: "DOTUSD", type: "crypto", priceDecimals: 2, glyph: "DO", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 43 },
  { id: "DOGEUSD", label: "Dogecoin (DOGE/USD)", symbol: "DOGEUSD", type: "crypto", priceDecimals: 2, glyph: "DG", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 44 },
  { id: "LINKUSD", label: "Chainlink (LINK/USD)", symbol: "LINKUSD", type: "crypto", priceDecimals: 2, glyph: "LK", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 45 },
  { id: "AVAXUSD", label: "Avalanche (AVAX/USD)", symbol: "AVAXUSD", type: "crypto", priceDecimals: 2, glyph: "AV", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 46 },
  { id: "BNBUSD", label: "BNB (BNB/USD)", symbol: "BNBUSD", type: "crypto", priceDecimals: 2, glyph: "BN", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 47 },
  { id: "TRXUSD", label: "TRON (TRX/USD)", symbol: "TRXUSD", type: "crypto", priceDecimals: 2, glyph: "TX", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 48 },
  { id: "XLMUSD", label: "Stellar (XLM/USD)", symbol: "XLMUSD", type: "crypto", priceDecimals: 2, glyph: "XL", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 49 },
  { id: "ATOMUSD", label: "Cosmos (ATOM/USD)", symbol: "ATOMUSD", type: "crypto", priceDecimals: 2, glyph: "AT", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 50 },
  { id: "UNIUSD", label: "Uniswap (UNI/USD)", symbol: "UNIUSD", type: "crypto", priceDecimals: 2, glyph: "UN", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 51 },
  { id: "ETCUSD", label: "Ethereum Classic (ETC/USD)", symbol: "ETCUSD", type: "crypto", priceDecimals: 2, glyph: "EC", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 52 },
  { id: "FILUSD", label: "Filecoin (FIL/USD)", symbol: "FILUSD", type: "crypto", priceDecimals: 2, glyph: "FL", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 53 },
  { id: "NEARUSD", label: "NEAR Protocol (NEAR/USD)", symbol: "NEARUSD", type: "crypto", priceDecimals: 2, glyph: "NR", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 54 },
  { id: "BTCEUR", label: "Bitcoin en euro (BTC/EUR)", symbol: "BTCEUR", type: "crypto", priceDecimals: 2, glyph: "₿", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 55 },
  { id: "ETHEUR", label: "Ethereum en euro (ETH/EUR)", symbol: "ETHEUR", type: "crypto", priceDecimals: 2, glyph: "Ξ", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 56 },
  { id: "SOLEUR", label: "Solana en euro (SOL/EUR)", symbol: "SOLEUR", type: "crypto", priceDecimals: 2, glyph: "SO", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 57 },
  { id: "BTCGBP", label: "Bitcoin en livre (BTC/GBP)", symbol: "BTCGBP", type: "crypto", priceDecimals: 2, glyph: "₿", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 58 },
  { id: "POLUSD", label: "Polygon / Dollar (POL/USD)", symbol: "POLUSD", type: "crypto", priceDecimals: 2, glyph: "P", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 59 },
  { id: "USDTRY", label: "Dollar / Livre turque (USD/TRY)", symbol: "USDTRY", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 60 },
  { id: "USDZAR", label: "Dollar / Rand (USD/ZAR)", symbol: "USDZAR", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 61 },
  { id: "USDMXN", label: "Dollar / Peso mexicain (USD/MXN)", symbol: "USDMXN", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 62 },
  { id: "USDSEK", label: "Dollar / Couronne suédoise (USD/SEK)", symbol: "USDSEK", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 63 },
  { id: "USDNOK", label: "Dollar / Couronne norvégienne (USD/NOK)", symbol: "USDNOK", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 64 },
  { id: "USDDKK", label: "Dollar / Couronne danoise (USD/DKK)", symbol: "USDDKK", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 65 },
  { id: "USDPLN", label: "Dollar / Zloty (USD/PLN)", symbol: "USDPLN", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 66 },
  { id: "USDHUF", label: "Dollar / Forint (USD/HUF)", symbol: "USDHUF", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 67 },
  { id: "USDCZK", label: "Dollar / Couronne tchèque (USD/CZK)", symbol: "USDCZK", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 68 },
  { id: "USDSGD", label: "Dollar / Dollar de Singapour (USD/SGD)", symbol: "USDSGD", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 69 },
  { id: "USDHKD", label: "Dollar / Dollar de Hong Kong (USD/HKD)", symbol: "USDHKD", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 70 },
  { id: "USDTHB", label: "Dollar / Baht (USD/THB)", symbol: "USDTHB", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 71 },
  { id: "USDCNH", label: "Dollar / Yuan offshore (USD/CNH)", symbol: "USDCNH", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 72 },
  { id: "USDINR", label: "Dollar / Roupie indienne (USD/INR)", symbol: "USDINR", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 73 },
  { id: "USDBRL", label: "Dollar / Réal (USD/BRL)", symbol: "USDBRL", type: "fx", priceDecimals: 5, glyph: "$", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 74 },
  { id: "EURTRY", label: "Euro / Livre turque (EUR/TRY)", symbol: "EURTRY", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 75 },
  { id: "EURZAR", label: "Euro / Rand (EUR/ZAR)", symbol: "EURZAR", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 76 },
  { id: "EURPLN", label: "Euro / Zloty (EUR/PLN)", symbol: "EURPLN", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 77 },
  { id: "EURSEK", label: "Euro / Couronne suédoise (EUR/SEK)", symbol: "EURSEK", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 78 },
  { id: "EURNOK", label: "Euro / Couronne norvégienne (EUR/NOK)", symbol: "EURNOK", type: "fx", priceDecimals: 5, glyph: "€", timeframes: ["M1", "M5", "M15", "H1", "H4", "D1"], index: 79 },
];
