'use client';

import * as React from 'react';
import { useTranslations } from 'next-intl';

/**
 * Renders one STATIC pedagogical help text (mission UI-2c) from the i18n bundle
 * (`reading.help.<key>` = `{ title, body[] }`). The texts are product
 * documentation — fixed strings, versioned and reviewed, NEVER generated by a
 * model at runtime. Inline `**bold**` markers become <b>; each paragraph a <p>.
 * The caller frames it in the card's `.infobox`.
 */
function withBold(text: string): React.ReactNode {
  // Split on `**`; odd segments are bold. No HTML injection — plain text only.
  return text.split('**').map((seg, i) =>
    i % 2 === 1 ? <b key={i}>{seg}</b> : <React.Fragment key={i}>{seg}</React.Fragment>,
  );
}

export function HelpContent({ helpKey }: { helpKey: string }) {
  const t = useTranslations('reading.help');
  const raw = t.raw(helpKey) as { title?: string; body?: string } | undefined;
  if (!raw || typeof raw !== 'object' || !raw.title || typeof raw.body !== 'string') {
    return null;
  }
  // Paragraphs are stored `\n\n`-joined in one string (next-intl messages can't
  // hold arrays); split them back out for rendering.
  const paragraphs = raw.body.split(/\n\n+/).filter(Boolean);
  return (
    <>
      <h4>{raw.title}</h4>
      {paragraphs.map((p, i) => (
        <p key={i}>{withBold(p)}</p>
      ))}
    </>
  );
}
