/**
 * DS-1 — Frozen sample data for the design gallery.
 *
 * REAL product data, copied from data/market_readings.db and data/candles.db
 * (the same payloads /app and /zones render live). NOT invented by hand.
 *
 * Generated by webapp/scripts/gen_ds_samples.py — do NOT edit by hand; re-run
 * the generator against the DB to refresh. Legacy payloads are normalised to
 * the current @/types/market-reading contract (see the script header for the
 * exact whitelist). No network, no secrets, no PII.
 */
import type { CalendarResponse, CalendarEvent } from '@/types/calendar';
import type { PublicationMeasures } from '@/types/measures';

export const SAMPLE_CALENDAR_MONTH: CalendarResponse = {
  "events": [
    {
      "event_id": "dae2270eae8ecc99",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "Core CPI Flash Estimate y/y",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T09:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 2.5,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "5276b24f77da5884",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "CPI Flash Estimate y/y",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T09:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 3.2,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "3881705ef9b9a031",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "ADP Non-Farm Employment Change",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T12:15:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 122000.0,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "962fa1059b944c3b",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "ECB President Lagarde Speaks",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T13:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "359deec167a3c250",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Fed Chairman Warsh Speaks",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T13:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "1319311607f11555",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "ECB President Lagarde Speaks",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T14:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "2fb66fb06848d09e",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "ISM Manufacturing PMI",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T14:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 54.0,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "d1b970f7a0cd4eac",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "ISM Manufacturing Prices",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T14:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 82.1,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "11164de1786759a7",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "President Trump Speaks",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-01T19:15:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "ff331bc2d148fa80",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Average Hourly Earnings m/m",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-02T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 0.3,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "8df6a98271c95e43",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Non-Farm Employment Change",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-02T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 172000.0,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "d549167d4972f5ae",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Unemployment Rate",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-02T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 4.3,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "4c9034bb9959bc17",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Unemployment Claims",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-02T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 215000.0,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "6f0f8f34bfb964fd",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "ECB President Lagarde Speaks",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-03T08:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-04T18:00:41Z"
    },
    {
      "event_id": "9b78c6e03df97a4c",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "President Trump Speaks",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-27T18:50:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "dcbf85b957f648eb",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "CB Consumer Confidence",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-28T14:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 91.2,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "f495faa1b6fa966e",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Federal Funds Rate",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-29T18:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 3.75,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "a1ad4be9a75598d7",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "FOMC Statement",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-29T18:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "97a3e674104a2e9d",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "FOMC Press Conference",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-29T18:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": null,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "e6cbfc8ae74f383d",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "German Prelim CPI m/m",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-30T06:29:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": -0.3,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "a4c20919f70e3006",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "German Prelim GDP q/q",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-30T08:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 0.3,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "7e546c057b32e5da",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Advance GDP q/q",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-30T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 2.0,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "6cf58672e2eabc59",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Core PCE Price Index m/m",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-30T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 0.3,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "c6d06d949e012c69",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Advance GDP Price Index q/q",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-30T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 3.6,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "c4f132882fea69b2",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Unemployment Claims",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-30T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 187000.0,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "42b9b12e27c92ab0",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "Core CPI Flash Estimate y/y",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-31T09:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 2.4,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "73e469d41ba3b163",
      "source": "eurostat",
      "series_code": null,
      "license_label": null,
      "event": "CPI Flash Estimate y/y",
      "currency": "EUR",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-31T09:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "EURUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 2.8,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "def9226045ff5448",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Employment Cost Index q/q",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-31T12:30:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 0.9,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "65755f3ddb3aca87",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Revised UoM Consumer Sentiment",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-31T14:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 54.4,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    },
    {
      "event_id": "4ac44cb1b05e7dd7",
      "source": "bls",
      "series_code": null,
      "license_label": null,
      "event": "Revised UoM Inflation Expectations",
      "currency": "USD",
      "organism": null,
      "periodicity": null,
      "scheduled_at": "2026-07-31T14:00:00Z",
      "source_timezone": null,
      "time_confirmed": true,
      "markets": [
        "XAUUSD"
      ],
      "value_unit": null,
      "actual": null,
      "actual_initial": null,
      "previous": 4.2,
      "revised": false,
      "revised_at": null,
      "actual_state": "unfetched",
      "refreshed_at": "2026-07-31T23:29:41Z"
    }
  ],
  "window_start": "2026-07-01T00:00:00Z",
  "window_end": "2026-07-31T23:59:59Z",
  "coverage": {
    "source": "forexfactory",
    "feed_start": "2026-07-01T00:00:00Z",
    "feed_end": "2026-07-31T23:59:59Z",
    "partial": false,
    "last_success": {
      "forexfactory": "2026-07-31T18:00:00Z"
    },
    "stale_sources": []
  },
  "attribution": [
    {
      "source": "forexfactory",
      "organism": "ForexFactory",
      "license_label": "Agenda économique public",
      "policy_url": "https://www.forexfactory.com/calendar"
    }
  ],
  "generated_at": "2026-07-31T18:00:00Z"
};

/** Deep-link target for /actualites/[eventId]. */
export const SAMPLE_CALENDAR_EVENT_ID = "dae2270eae8ecc99";

export const SAMPLE_CALENDAR_EVENT: CalendarEvent = {
  "event_id": "dae2270eae8ecc99",
  "source": "eurostat",
  "series_code": null,
  "license_label": null,
  "event": "Core CPI Flash Estimate y/y",
  "currency": "EUR",
  "organism": null,
  "periodicity": null,
  "scheduled_at": "2026-07-01T09:00:00Z",
  "source_timezone": null,
  "time_confirmed": true,
  "markets": [
    "EURUSD"
  ],
  "value_unit": null,
  "actual": null,
  "actual_initial": null,
  "previous": 2.5,
  "revised": false,
  "revised_at": null,
  "actual_state": "unfetched",
  "refreshed_at": "2026-07-04T18:00:41Z"
};

/** No measure computed for a stub-feed event → the fiche renders no measure section (absence). */
export const SAMPLE_CALENDAR_MEASURES: PublicationMeasures = {
  "event_key": "dae2270eae8ecc99",
  "market": "EURUSD",
  "calm_before": null,
  "structure_state": null,
  "zone_lifecycle": null,
  "return_to_calm": null
};
