/**
 * DS-1 — Frozen sample data for the design gallery.
 *
 * REAL product data, copied from data/market_readings.db and data/candles.db
 * (the same payloads /app and /zones render live). NOT invented by hand.
 *
 * Generated by webapp/scripts/gen_ds_samples.py — do NOT edit by hand; re-run
 * the generator against the DB to refresh. Legacy payloads are normalised to
 * the current @/types/market-reading contract (see the script header for the
 * exact whitelist). No network, no secrets, no PII.
 */
import type { MarketReading } from '@/types/market-reading';

export const SAMPLE_READING_XAU_H4: MarketReading = {
  "schema_version": "2.0.0",
  "header": {
    "instrument": "XAUUSD",
    "timeframe": "H4",
    "candle_close_ts": "2026-07-31T20:00:00Z",
    "close_price": 4043.24,
    "analysis_window_bars": 499
  },
  "structure": {
    "current_bos": null,
    "current_choch": null,
    "order_blocks": [
      {
        "id": "OB_bearish_20260605120000",
        "direction": "bearish",
        "level_high": 4468.19,
        "level_low": 4428.81,
        "importance": "high",
        "status": "active",
        "created_at": "2026-06-05T12:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260512040000",
        "direction": "bearish",
        "level_high": 4773.42,
        "level_low": 4735.18,
        "importance": "high",
        "status": "active",
        "created_at": "2026-05-12T04:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260514160000",
        "direction": "bearish",
        "level_high": 4710.06,
        "level_low": 4688.48,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-05-14T16:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260618080000",
        "direction": "bearish",
        "level_high": 4329.91,
        "level_low": 4307.05,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-06-18T08:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260421040000",
        "direction": "bearish",
        "level_high": 4833.24,
        "level_low": 4816.89,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-04-21T04:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260630080000",
        "direction": "bullish",
        "level_high": 3998.0,
        "level_low": 3942.48,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-30T08:00:00Z",
        "tested": true,
        "mitigated_at": "2026-07-01T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260604160000",
        "direction": "bearish",
        "level_high": 4514.74,
        "level_low": 4461.1,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-04T16:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-04T20:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260717160000",
        "direction": "bullish",
        "level_high": 4002.45,
        "level_low": 3964.05,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-17T16:00:00Z",
        "tested": true,
        "mitigated_at": "2026-07-17T20:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260728160000",
        "direction": "bullish",
        "level_high": 4045.91,
        "level_low": 4016.89,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-28T16:00:00Z",
        "tested": true,
        "mitigated_at": "2026-07-28T20:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260601040000",
        "direction": "bearish",
        "level_high": 4546.06,
        "level_low": 4509.54,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-01T04:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-01T08:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260617200000",
        "direction": "bearish",
        "level_high": 4366.49,
        "level_low": 4324.1,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-17T20:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-18T04:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260602120000",
        "direction": "bearish",
        "level_high": 4541.46,
        "level_low": 4515.24,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-02T12:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-02T16:00:00Z",
        "user_flagged": false
      }
    ],
    "fair_value_gaps": [
      {
        "id": "FVG_bearish_20260515040000",
        "direction": "bearish",
        "level_high": 4653.03,
        "level_low": 4631.68,
        "status": "active",
        "created_at": "2026-05-15T04:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260731120000",
        "direction": "bearish",
        "level_high": 4071.97,
        "level_low": 4063.94,
        "status": "active",
        "created_at": "2026-07-31T12:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260515080000",
        "direction": "bearish",
        "level_high": 4613.61,
        "level_low": 4606.45,
        "status": "active",
        "created_at": "2026-05-15T08:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260605160000",
        "direction": "bearish",
        "level_high": 4428.81,
        "level_low": 4421.02,
        "status": "active",
        "created_at": "2026-06-05T16:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260514200000",
        "direction": "bearish",
        "level_high": 4688.48,
        "level_low": 4682.99,
        "status": "active",
        "created_at": "2026-05-14T20:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260618200000",
        "direction": "bearish",
        "level_high": 4239.95,
        "level_low": 4233.19,
        "status": "active",
        "created_at": "2026-06-18T20:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260731160000",
        "direction": "bearish",
        "level_high": 4054.06,
        "level_low": 4052.62,
        "status": "active",
        "created_at": "2026-07-31T16:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260515000000",
        "direction": "bearish",
        "level_high": 4666.65,
        "level_low": 4665.28,
        "status": "active",
        "created_at": "2026-05-15T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260605200000",
        "direction": "bearish",
        "level_high": 4404.82,
        "level_low": 4347.52,
        "status": "partially_filled",
        "created_at": "2026-06-05T20:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-08T00:00:00Z",
        "fill_level": 4382.48,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260515120000",
        "direction": "bearish",
        "level_high": 4604.45,
        "level_low": 4572.58,
        "status": "partially_filled",
        "created_at": "2026-05-15T12:00:00Z",
        "tested": true,
        "mitigated_at": "2026-05-18T12:00:00Z",
        "fill_level": 4595.18,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260618120000",
        "direction": "bearish",
        "level_high": 4307.05,
        "level_low": 4273.33,
        "status": "partially_filled",
        "created_at": "2026-06-18T12:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-18T16:00:00Z",
        "fill_level": 4276.73,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260421080000",
        "direction": "bearish",
        "level_high": 4816.89,
        "level_low": 4797.0,
        "status": "partially_filled",
        "created_at": "2026-04-21T08:00:00Z",
        "tested": true,
        "mitigated_at": "2026-04-21T12:00:00Z",
        "fill_level": 4797.95,
        "user_flagged": false
      }
    ],
    "bos_events": [
      {
        "direction": "bearish",
        "level": 4044.44,
        "broken_at": "2026-07-24T04:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 33
      },
      {
        "direction": "bullish",
        "level": 4141.62,
        "broken_at": "2026-07-22T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 42
      },
      {
        "direction": "bullish",
        "level": 4084.13,
        "broken_at": "2026-07-21T20:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 47
      },
      {
        "direction": "bullish",
        "level": 4040.66,
        "broken_at": "2026-07-21T04:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 51
      },
      {
        "direction": "bullish",
        "level": 4008.57,
        "broken_at": "2026-07-17T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 60
      },
      {
        "direction": "bearish",
        "level": 3969.1,
        "broken_at": "2026-07-17T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 61
      },
      {
        "direction": "bearish",
        "level": 3998.58,
        "broken_at": "2026-07-13T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 84
      },
      {
        "direction": "bullish",
        "level": 4144.9,
        "broken_at": "2026-07-03T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 124
      },
      {
        "direction": "bearish",
        "level": 4023.74,
        "broken_at": "2026-06-24T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 163
      },
      {
        "direction": "bearish",
        "level": 4268.51,
        "broken_at": "2026-06-09T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 228
      },
      {
        "direction": "bearish",
        "level": 4366.52,
        "broken_at": "2026-06-05T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 240
      },
      {
        "direction": "bullish",
        "level": 4538.08,
        "broken_at": "2026-05-29T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 270
      },
      {
        "direction": "bearish",
        "level": 4401.52,
        "broken_at": "2026-05-28T04:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 279
      },
      {
        "direction": "bearish",
        "level": 4464.68,
        "broken_at": "2026-05-20T04:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 315
      },
      {
        "direction": "bearish",
        "level": 4546.14,
        "broken_at": "2026-05-15T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 331
      },
      {
        "direction": "bullish",
        "level": 4722.87,
        "broken_at": "2026-05-07T08:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 368
      },
      {
        "direction": "bullish",
        "level": 4660.16,
        "broken_at": "2026-05-06T08:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 374
      },
      {
        "direction": "bullish",
        "level": 4610.25,
        "broken_at": "2026-04-30T08:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 398
      },
      {
        "direction": "bearish",
        "level": 4554.83,
        "broken_at": "2026-04-29T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 403
      }
    ],
    "choch_events": [
      {
        "direction": "bearish",
        "level": 4044.44,
        "broken_at": "2026-07-24T04:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 33
      },
      {
        "direction": "bullish",
        "level": 4008.57,
        "broken_at": "2026-07-17T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 60
      },
      {
        "direction": "bearish",
        "level": 3998.58,
        "broken_at": "2026-07-13T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 84
      },
      {
        "direction": "bullish",
        "level": 4144.9,
        "broken_at": "2026-07-03T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 124
      },
      {
        "direction": "bearish",
        "level": 4366.52,
        "broken_at": "2026-06-05T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 240
      },
      {
        "direction": "bullish",
        "level": 4538.08,
        "broken_at": "2026-05-29T16:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 270
      },
      {
        "direction": "bearish",
        "level": 4546.14,
        "broken_at": "2026-05-15T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 331
      },
      {
        "direction": "bullish",
        "level": 4610.25,
        "broken_at": "2026-04-30T08:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 398
      }
    ],
    "liquidity_pools": [
      {
        "id": "LIQ_ssl_range_low_20260630120000",
        "side": "ssl",
        "kind": "range_low",
        "level": 3942.48,
        "touches": 1,
        "is_external": true,
        "status": "intact",
        "created_at": "2026-06-30T12:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_range_high_20260618040000",
        "side": "bsl",
        "kind": "range_high",
        "level": 4382.48,
        "touches": 1,
        "is_external": true,
        "status": "intact",
        "created_at": "2026-06-18T04:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260721000000",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 3995.92,
        "touches": 2,
        "is_external": false,
        "status": "intact",
        "created_at": "2026-07-21T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260727080000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4116.23,
        "touches": 2,
        "is_external": false,
        "status": "swept",
        "created_at": "2026-07-27T08:00:00Z",
        "swept_at": "2026-07-30T16:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260727080000",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 4009.11,
        "touches": 2,
        "is_external": false,
        "status": "swept",
        "created_at": "2026-07-27T08:00:00Z",
        "swept_at": "2026-07-29T16:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260625040000",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 3958.96,
        "touches": 3,
        "is_external": false,
        "status": "swept",
        "created_at": "2026-06-25T04:00:00Z",
        "swept_at": "2026-06-30T04:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260623120000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4198.57,
        "touches": 2,
        "is_external": false,
        "status": "swept",
        "created_at": "2026-06-23T12:00:00Z",
        "swept_at": "2026-07-06T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260716040000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4084.13,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-07-16T04:00:00Z",
        "broken_at": "2026-07-21T20:00:00Z",
        "user_flagged": false
      }
    ]
  },
  "regime": {
    "trend": "bearish",
    "volatility_observed": "normal",
    "market_phase": "trend",
    "mtf_confluence": {
      "d1": "bearish"
    },
    "volatility_detail": {
      "recent_avg": 33.14142857142867,
      "baseline_avg": 33.175499999999985,
      "ratio": 0.9989729942707324,
      "recent_n": 7,
      "baseline_n": 20,
      "threshold_low": 0.7,
      "threshold_high": 1.3
    },
    "trend_reference": {
      "kind": "choch",
      "direction": "bearish",
      "level": 4044.44,
      "broken_at": "2026-07-24T04:00:00Z",
      "bars_ago": 33
    }
  },
  "events": {
    "news_upcoming": [],
    "news_just_published": [
      {
        "event": "Core CPI Flash Estimate y/y",
        "published_at": "2026-07-31T09:00:00Z",
        "forecast": 2.4,
        "previous": 2.4,
        "currency": "EUR",
        "impact": "medium",
        "potential_effect_description": "Core CPI Flash Estimate y/y (EUR) — impact moyen, publié il y a 13h30.",
        "event_id": "42b9b12e27c92ab0"
      },
      {
        "event": "CPI Flash Estimate y/y",
        "published_at": "2026-07-31T09:00:00Z",
        "forecast": 2.9,
        "previous": 2.8,
        "currency": "EUR",
        "impact": "medium",
        "potential_effect_description": "CPI Flash Estimate y/y (EUR) — impact moyen, publié il y a 13h30.",
        "event_id": "73e469d41ba3b163"
      },
      {
        "event": "Employment Cost Index q/q",
        "published_at": "2026-07-31T12:30:00Z",
        "forecast": 0.8,
        "previous": 0.9,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Employment Cost Index q/q (USD) — impact moyen, publié il y a 10h.",
        "event_id": "def9226045ff5448"
      },
      {
        "event": "Revised UoM Consumer Sentiment",
        "published_at": "2026-07-31T14:00:00Z",
        "forecast": 53.9,
        "previous": 54.4,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Revised UoM Consumer Sentiment (USD) — impact moyen, publié il y a 8h30.",
        "event_id": "65755f3ddb3aca87"
      },
      {
        "event": "Revised UoM Inflation Expectations",
        "published_at": "2026-07-31T14:00:00Z",
        "previous": 4.2,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Revised UoM Inflation Expectations (USD) — impact moyen, publié il y a 8h30.",
        "event_id": "4ac44cb1b05e7dd7"
      }
    ],
    "technical_triggers_recent": []
  },
  "conditions": {
    "tags": [
      "trend_bearish",
      "volatility_normal",
      "phase_trend",
      "ob_active",
      "fvg_active",
      "mtf_aligned"
    ],
    "description": "Tendance baissière, volatilité normale, phase de tendance. Les timeframes supérieurs sont alignés baissiers. À proximité : une FVG baissier actif (non testé) au-dessus du prix (4 052,62–4 054,06) ; une FVG baissier actif (non testé) au-dessus du prix (4 063,94–4 071,97).",
    "description_source": "engine_template"
  }
};

export const SAMPLE_READING_EUR_M15: MarketReading = {
  "schema_version": "2.0.0",
  "header": {
    "instrument": "EURUSD",
    "timeframe": "M15",
    "candle_close_ts": "2026-07-31T21:00:00Z",
    "close_price": 1.15312,
    "analysis_window_bars": 2876
  },
  "structure": {
    "current_bos": {
      "direction": "bullish",
      "level": 1.1519300000000001,
      "broken_at": "2026-07-31T18:00:00Z",
      "validation_status": "confirmed"
    },
    "current_choch": null,
    "order_blocks": [
      {
        "id": "OB_bullish_20260729193000",
        "direction": "bullish",
        "level_high": 1.14298,
        "level_low": 1.14151,
        "importance": "high",
        "status": "active",
        "created_at": "2026-07-29T19:30:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260730100000",
        "direction": "bullish",
        "level_high": 1.14543,
        "level_low": 1.14467,
        "importance": "high",
        "status": "active",
        "created_at": "2026-07-30T10:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260624141500",
        "direction": "bullish",
        "level_high": 1.13318,
        "level_low": 1.1324,
        "importance": "high",
        "status": "active",
        "created_at": "2026-06-24T14:15:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260625133000",
        "direction": "bullish",
        "level_high": 1.13427,
        "level_low": 1.13384,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-06-25T13:30:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260731161500",
        "direction": "bullish",
        "level_high": 1.15077,
        "level_low": 1.14972,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-31T16:15:00Z",
        "tested": true,
        "mitigated_at": "2026-07-31T16:30:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260729133000",
        "direction": "bullish",
        "level_high": 1.13799,
        "level_low": 1.13746,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-29T13:30:00Z",
        "tested": true,
        "mitigated_at": "2026-07-29T13:45:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260626033000",
        "direction": "bullish",
        "level_high": 1.13592,
        "level_low": 1.13541,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-26T03:30:00Z",
        "tested": true,
        "mitigated_at": "2026-06-26T03:45:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260728121500",
        "direction": "bullish",
        "level_high": 1.13613,
        "level_low": 1.13567,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-28T12:15:00Z",
        "tested": true,
        "mitigated_at": "2026-07-28T12:45:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260624160000",
        "direction": "bullish",
        "level_high": 1.13437,
        "level_low": 1.13353,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-24T16:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-24T22:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260728113000",
        "direction": "bullish",
        "level_high": 1.13577,
        "level_low": 1.13547,
        "importance": "medium",
        "status": "mitigated",
        "created_at": "2026-07-28T11:30:00Z",
        "tested": true,
        "mitigated_at": "2026-07-28T11:45:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260730124500",
        "direction": "bullish",
        "level_high": 1.1468099999999999,
        "level_low": 1.1465,
        "importance": "medium",
        "status": "mitigated",
        "created_at": "2026-07-30T12:45:00Z",
        "tested": true,
        "mitigated_at": "2026-07-31T14:30:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260731201500",
        "direction": "bearish",
        "level_high": 1.15344,
        "level_low": 1.15308,
        "importance": "medium",
        "status": "mitigated",
        "created_at": "2026-07-31T20:15:00Z",
        "tested": true,
        "mitigated_at": "2026-07-31T20:30:00Z",
        "user_flagged": false
      }
    ],
    "fair_value_gaps": [
      {
        "id": "FVG_bullish_20260731154500",
        "direction": "bullish",
        "level_high": 1.14894,
        "level_low": 1.14804,
        "status": "active",
        "created_at": "2026-07-31T15:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260729181500",
        "direction": "bullish",
        "level_high": 1.13888,
        "level_low": 1.1386,
        "status": "active",
        "created_at": "2026-07-29T18:15:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260731153000",
        "direction": "bullish",
        "level_high": 1.14796,
        "level_low": 1.14749,
        "status": "active",
        "created_at": "2026-07-31T15:30:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260731160000",
        "direction": "bullish",
        "level_high": 1.14972,
        "level_low": 1.14924,
        "status": "active",
        "created_at": "2026-07-31T16:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260729194500",
        "direction": "bullish",
        "level_high": 1.14337,
        "level_low": 1.14298,
        "status": "active",
        "created_at": "2026-07-29T19:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260729180000",
        "direction": "bullish",
        "level_high": 1.13845,
        "level_low": 1.13826,
        "status": "active",
        "created_at": "2026-07-29T18:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260731181500",
        "direction": "bullish",
        "level_high": 1.152,
        "level_low": 1.15182,
        "status": "active",
        "created_at": "2026-07-31T18:15:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260728140000",
        "direction": "bullish",
        "level_high": 1.13658,
        "level_low": 1.13653,
        "status": "active",
        "created_at": "2026-07-28T14:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260731164500",
        "direction": "bullish",
        "level_high": 1.15087,
        "level_low": 1.1508099999999999,
        "status": "active",
        "created_at": "2026-07-31T16:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260728150000",
        "direction": "bullish",
        "level_high": 1.13711,
        "level_low": 1.13709,
        "status": "active",
        "created_at": "2026-07-28T15:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260729191500",
        "direction": "bullish",
        "level_high": 1.14151,
        "level_low": 1.13999,
        "status": "partially_filled",
        "created_at": "2026-07-29T19:15:00Z",
        "tested": true,
        "mitigated_at": "2026-07-29T19:30:00Z",
        "fill_level": 1.14069,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260625134500",
        "direction": "bullish",
        "level_high": 1.13521,
        "level_low": 1.13427,
        "status": "partially_filled",
        "created_at": "2026-06-25T13:45:00Z",
        "tested": true,
        "mitigated_at": "2026-06-25T14:00:00Z",
        "fill_level": 1.1348,
        "user_flagged": false
      }
    ],
    "bos_events": [
      {
        "direction": "bullish",
        "level": 1.1519300000000001,
        "broken_at": "2026-07-31T18:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 11
      },
      {
        "direction": "bullish",
        "level": 1.15038,
        "broken_at": "2026-07-31T15:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 20
      },
      {
        "direction": "bearish",
        "level": 1.14694,
        "broken_at": "2026-07-31T14:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 24
      },
      {
        "direction": "bullish",
        "level": 1.14843,
        "broken_at": "2026-07-30T14:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 121
      },
      {
        "direction": "bullish",
        "level": 1.1471,
        "broken_at": "2026-07-29T23:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 180
      },
      {
        "direction": "bullish",
        "level": 1.14668,
        "broken_at": "2026-07-29T21:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 188
      },
      {
        "direction": "bullish",
        "level": 1.14053,
        "broken_at": "2026-07-29T19:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 199
      },
      {
        "direction": "bullish",
        "level": 1.1373199999999999,
        "broken_at": "2026-07-28T15:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 311
      },
      {
        "direction": "bearish",
        "level": 1.13617,
        "broken_at": "2026-07-28T10:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 328
      },
      {
        "direction": "bearish",
        "level": 1.13683,
        "broken_at": "2026-07-27T20:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 387
      },
      {
        "direction": "bearish",
        "level": 1.13763,
        "broken_at": "2026-07-27T14:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 408
      },
      {
        "direction": "bearish",
        "level": 1.13934,
        "broken_at": "2026-07-27T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 419
      },
      {
        "direction": "bearish",
        "level": 1.14005,
        "broken_at": "2026-07-27T08:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 432
      },
      {
        "direction": "bullish",
        "level": 1.14131,
        "broken_at": "2026-07-27T02:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 456
      },
      {
        "direction": "bullish",
        "level": 1.1400000000000001,
        "broken_at": "2026-07-27T01:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 463
      },
      {
        "direction": "bullish",
        "level": 1.13908,
        "broken_at": "2026-07-26T22:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 475
      },
      {
        "direction": "bearish",
        "level": 1.13712,
        "broken_at": "2026-07-24T13:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 509
      },
      {
        "direction": "bearish",
        "level": 1.13764,
        "broken_at": "2026-07-24T12:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 512
      },
      {
        "direction": "bullish",
        "level": 1.13877,
        "broken_at": "2026-07-24T08:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 531
      },
      {
        "direction": "bearish",
        "level": 1.13681,
        "broken_at": "2026-07-23T15:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 597
      },
      {
        "direction": "bearish",
        "level": 1.13833,
        "broken_at": "2026-07-23T13:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 605
      },
      {
        "direction": "bearish",
        "level": 1.1407,
        "broken_at": "2026-07-23T11:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 613
      },
      {
        "direction": "bearish",
        "level": 1.1416,
        "broken_at": "2026-07-23T09:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 621
      },
      {
        "direction": "bullish",
        "level": 1.14218,
        "broken_at": "2026-07-23T03:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 645
      },
      {
        "direction": "bullish",
        "level": 1.14139,
        "broken_at": "2026-07-22T14:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 698
      },
      {
        "direction": "bearish",
        "level": 1.14034,
        "broken_at": "2026-07-22T11:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 711
      },
      {
        "direction": "bearish",
        "level": 1.14054,
        "broken_at": "2026-07-22T09:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 719
      },
      {
        "direction": "bullish",
        "level": 1.14103,
        "broken_at": "2026-07-22T07:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 727
      },
      {
        "direction": "bullish",
        "level": 1.14073,
        "broken_at": "2026-07-22T03:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 742
      },
      {
        "direction": "bullish",
        "level": 1.14042,
        "broken_at": "2026-07-22T01:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 750
      },
      {
        "direction": "bearish",
        "level": 1.13986,
        "broken_at": "2026-07-21T21:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 764
      },
      {
        "direction": "bearish",
        "level": 1.14024,
        "broken_at": "2026-07-21T19:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 775
      },
      {
        "direction": "bearish",
        "level": 1.14169,
        "broken_at": "2026-07-20T14:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 889
      },
      {
        "direction": "bearish",
        "level": 1.14302,
        "broken_at": "2026-07-17T11:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 996
      },
      {
        "direction": "bullish",
        "level": 1.14625,
        "broken_at": "2026-07-15T18:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1161
      },
      {
        "direction": "bullish",
        "level": 1.1406,
        "broken_at": "2026-07-14T12:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1280
      },
      {
        "direction": "bullish",
        "level": 1.13968,
        "broken_at": "2026-07-14T09:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1294
      },
      {
        "direction": "bullish",
        "level": 1.1389,
        "broken_at": "2026-07-14T03:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1319
      },
      {
        "direction": "bearish",
        "level": 1.13817,
        "broken_at": "2026-07-13T21:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1343
      },
      {
        "direction": "bearish",
        "level": 1.13827,
        "broken_at": "2026-07-13T20:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1347
      },
      {
        "direction": "bearish",
        "level": 1.13957,
        "broken_at": "2026-07-13T17:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1358
      },
      {
        "direction": "bullish",
        "level": 1.14184,
        "broken_at": "2026-07-13T08:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1392
      },
      {
        "direction": "bearish",
        "level": 1.13912,
        "broken_at": "2026-07-12T23:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1431
      },
      {
        "direction": "bullish",
        "level": 1.14212,
        "broken_at": "2026-07-02T13:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2045
      },
      {
        "direction": "bullish",
        "level": 1.1404,
        "broken_at": "2026-07-01T14:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2137
      },
      {
        "direction": "bearish",
        "level": 1.13886,
        "broken_at": "2026-07-01T10:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2152
      },
      {
        "direction": "bullish",
        "level": 1.14096,
        "broken_at": "2026-06-30T15:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2230
      },
      {
        "direction": "bullish",
        "level": 1.13992,
        "broken_at": "2026-06-30T07:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2260
      },
      {
        "direction": "bearish",
        "level": 1.13863,
        "broken_at": "2026-06-30T06:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2264
      },
      {
        "direction": "bearish",
        "level": 1.14004,
        "broken_at": "2026-06-30T04:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2274
      },
      {
        "direction": "bullish",
        "level": 1.14151,
        "broken_at": "2026-06-29T15:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2326
      },
      {
        "direction": "bullish",
        "level": 1.13936,
        "broken_at": "2026-06-29T06:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2360
      },
      {
        "direction": "bearish",
        "level": 1.13845,
        "broken_at": "2026-06-29T04:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2368
      },
      {
        "direction": "bullish",
        "level": 1.13922,
        "broken_at": "2026-06-29T03:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2374
      },
      {
        "direction": "bearish",
        "level": 1.13827,
        "broken_at": "2026-06-26T20:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2402
      },
      {
        "direction": "bearish",
        "level": 1.13922,
        "broken_at": "2026-06-26T17:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2414
      },
      {
        "direction": "bullish",
        "level": 1.14123,
        "broken_at": "2026-06-26T13:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2428
      },
      {
        "direction": "bullish",
        "level": 1.13838,
        "broken_at": "2026-06-25T16:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2514
      },
      {
        "direction": "bearish",
        "level": 1.13446,
        "broken_at": "2026-06-25T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2531
      },
      {
        "direction": "bullish",
        "level": 1.13651,
        "broken_at": "2026-06-25T09:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2542
      },
      {
        "direction": "bearish",
        "level": 1.1356,
        "broken_at": "2026-06-25T07:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2548
      },
      {
        "direction": "bullish",
        "level": 1.13681,
        "broken_at": "2026-06-25T04:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2560
      },
      {
        "direction": "bullish",
        "level": 1.13523,
        "broken_at": "2026-06-24T16:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2610
      },
      {
        "direction": "bearish",
        "level": 1.13368,
        "broken_at": "2026-06-24T13:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2621
      },
      {
        "direction": "bearish",
        "level": 1.13509,
        "broken_at": "2026-06-24T09:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2639
      },
      {
        "direction": "bearish",
        "level": 1.13605,
        "broken_at": "2026-06-24T07:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2644
      },
      {
        "direction": "bearish",
        "level": 1.13708,
        "broken_at": "2026-06-24T03:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2660
      },
      {
        "direction": "bearish",
        "level": 1.13731,
        "broken_at": "2026-06-24T02:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2666
      },
      {
        "direction": "bearish",
        "level": 1.13752,
        "broken_at": "2026-06-24T01:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2670
      },
      {
        "direction": "bearish",
        "level": 1.13826,
        "broken_at": "2026-06-23T15:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2710
      },
      {
        "direction": "bearish",
        "level": 1.14044,
        "broken_at": "2026-06-23T11:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2724
      },
      {
        "direction": "bearish",
        "level": 1.14186,
        "broken_at": "2026-06-23T08:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2737
      },
      {
        "direction": "bullish",
        "level": 1.1432,
        "broken_at": "2026-06-23T08:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2738
      },
      {
        "direction": "bearish",
        "level": 1.14252,
        "broken_at": "2026-06-22T19:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2788
      },
      {
        "direction": "bearish",
        "level": 1.14414,
        "broken_at": "2026-06-22T14:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2810
      }
    ],
    "choch_events": [
      {
        "direction": "bullish",
        "level": 1.15038,
        "broken_at": "2026-07-31T15:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 20
      },
      {
        "direction": "bearish",
        "level": 1.14694,
        "broken_at": "2026-07-31T14:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 24
      },
      {
        "direction": "bullish",
        "level": 1.1373199999999999,
        "broken_at": "2026-07-28T15:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 311
      },
      {
        "direction": "bearish",
        "level": 1.14005,
        "broken_at": "2026-07-27T08:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 432
      },
      {
        "direction": "bullish",
        "level": 1.13908,
        "broken_at": "2026-07-26T22:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 475
      },
      {
        "direction": "bearish",
        "level": 1.13764,
        "broken_at": "2026-07-24T12:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 512
      },
      {
        "direction": "bullish",
        "level": 1.13877,
        "broken_at": "2026-07-24T08:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 531
      },
      {
        "direction": "bearish",
        "level": 1.1416,
        "broken_at": "2026-07-23T09:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 621
      },
      {
        "direction": "bullish",
        "level": 1.14139,
        "broken_at": "2026-07-22T14:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 698
      },
      {
        "direction": "bearish",
        "level": 1.14054,
        "broken_at": "2026-07-22T09:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 719
      },
      {
        "direction": "bullish",
        "level": 1.14042,
        "broken_at": "2026-07-22T01:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 750
      },
      {
        "direction": "bearish",
        "level": 1.14302,
        "broken_at": "2026-07-17T11:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 996
      },
      {
        "direction": "bullish",
        "level": 1.1389,
        "broken_at": "2026-07-14T03:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1319
      },
      {
        "direction": "bearish",
        "level": 1.13957,
        "broken_at": "2026-07-13T17:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1358
      },
      {
        "direction": "bullish",
        "level": 1.14184,
        "broken_at": "2026-07-13T08:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1392
      },
      {
        "direction": "bearish",
        "level": 1.13912,
        "broken_at": "2026-07-12T23:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 1431
      },
      {
        "direction": "bullish",
        "level": 1.1404,
        "broken_at": "2026-07-01T14:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2137
      },
      {
        "direction": "bearish",
        "level": 1.13886,
        "broken_at": "2026-07-01T10:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2152
      },
      {
        "direction": "bullish",
        "level": 1.13992,
        "broken_at": "2026-06-30T07:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2260
      },
      {
        "direction": "bearish",
        "level": 1.14004,
        "broken_at": "2026-06-30T04:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2274
      },
      {
        "direction": "bullish",
        "level": 1.13936,
        "broken_at": "2026-06-29T06:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2360
      },
      {
        "direction": "bearish",
        "level": 1.13845,
        "broken_at": "2026-06-29T04:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2368
      },
      {
        "direction": "bullish",
        "level": 1.13922,
        "broken_at": "2026-06-29T03:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2374
      },
      {
        "direction": "bearish",
        "level": 1.13922,
        "broken_at": "2026-06-26T17:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2414
      },
      {
        "direction": "bullish",
        "level": 1.13838,
        "broken_at": "2026-06-25T16:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2514
      },
      {
        "direction": "bearish",
        "level": 1.13446,
        "broken_at": "2026-06-25T12:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2531
      },
      {
        "direction": "bullish",
        "level": 1.13651,
        "broken_at": "2026-06-25T09:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2542
      },
      {
        "direction": "bearish",
        "level": 1.1356,
        "broken_at": "2026-06-25T07:45:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2548
      },
      {
        "direction": "bullish",
        "level": 1.13523,
        "broken_at": "2026-06-24T16:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2610
      },
      {
        "direction": "bearish",
        "level": 1.14186,
        "broken_at": "2026-06-23T08:30:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2737
      },
      {
        "direction": "bullish",
        "level": 1.1432,
        "broken_at": "2026-06-23T08:15:00Z",
        "validation_status": "confirmed",
        "bars_ago": 2738
      }
    ],
    "liquidity_pools": [
      {
        "id": "LIQ_bsl_equal_highs_20260730153000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 1.1537600000000001,
        "touches": 2,
        "is_external": true,
        "status": "intact",
        "created_at": "2026-07-30T15:30:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_range_low_20260730090000",
        "side": "ssl",
        "kind": "range_low",
        "level": 1.14343,
        "touches": 1,
        "is_external": true,
        "status": "intact",
        "created_at": "2026-07-30T09:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260730193000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 1.15358,
        "touches": 2,
        "is_external": false,
        "status": "swept",
        "created_at": "2026-07-30T19:30:00Z",
        "swept_at": "2026-07-31T18:30:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260731014500",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 1.15266,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-07-31T01:45:00Z",
        "broken_at": "2026-07-31T18:15:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260731061500",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 1.15043,
        "touches": 3,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-07-31T06:15:00Z",
        "broken_at": "2026-07-31T10:30:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260731030000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 1.15223,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-07-31T03:00:00Z",
        "swept_at": "2026-07-31T08:45:00Z",
        "broken_at": "2026-07-31T18:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260730081500",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 1.14512,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-07-30T08:15:00Z",
        "broken_at": "2026-07-30T09:15:00Z",
        "user_flagged": false
      }
    ],
    "retest_in_progress": {
      "level": 1.1519300000000001,
      "type": "bos_retest",
      "started_at": "2026-07-31T21:00:00Z"
    }
  },
  "regime": {
    "trend": "bullish",
    "volatility_observed": "low",
    "market_phase": "trend",
    "mtf_confluence": {
      "h1": "bullish",
      "h4": "bullish"
    },
    "volatility_detail": {
      "recent_avg": 0.00047999999999997253,
      "baseline_avg": 0.0011464999999999837,
      "ratio": 0.41866550370691613,
      "recent_n": 7,
      "baseline_n": 20,
      "threshold_low": 0.7,
      "threshold_high": 1.3
    },
    "trend_reference": {
      "kind": "choch",
      "direction": "bullish",
      "level": 1.15038,
      "broken_at": "2026-07-31T15:45:00Z",
      "bars_ago": 20
    }
  },
  "events": {
    "news_upcoming": [],
    "news_just_published": [
      {
        "event": "Core CPI Flash Estimate y/y",
        "published_at": "2026-07-31T09:00:00Z",
        "forecast": 2.4,
        "previous": 2.4,
        "currency": "EUR",
        "impact": "medium",
        "potential_effect_description": "Core CPI Flash Estimate y/y (EUR) — impact moyen, publié il y a 12h31.",
        "event_id": "42b9b12e27c92ab0"
      },
      {
        "event": "CPI Flash Estimate y/y",
        "published_at": "2026-07-31T09:00:00Z",
        "forecast": 2.9,
        "previous": 2.8,
        "currency": "EUR",
        "impact": "medium",
        "potential_effect_description": "CPI Flash Estimate y/y (EUR) — impact moyen, publié il y a 12h31.",
        "event_id": "73e469d41ba3b163"
      },
      {
        "event": "Employment Cost Index q/q",
        "published_at": "2026-07-31T12:30:00Z",
        "forecast": 0.8,
        "previous": 0.9,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Employment Cost Index q/q (USD) — impact moyen, publié il y a 9h01.",
        "event_id": "def9226045ff5448"
      },
      {
        "event": "Revised UoM Consumer Sentiment",
        "published_at": "2026-07-31T14:00:00Z",
        "forecast": 53.9,
        "previous": 54.4,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Revised UoM Consumer Sentiment (USD) — impact moyen, publié il y a 7h31.",
        "event_id": "65755f3ddb3aca87"
      },
      {
        "event": "Revised UoM Inflation Expectations",
        "published_at": "2026-07-31T14:00:00Z",
        "previous": 4.2,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Revised UoM Inflation Expectations (USD) — impact moyen, publié il y a 7h31.",
        "event_id": "4ac44cb1b05e7dd7"
      }
    ],
    "technical_triggers_recent": []
  },
  "conditions": {
    "tags": [
      "trend_bullish",
      "volatility_low",
      "phase_trend",
      "bos_recent_bullish",
      "retest_in_progress",
      "ob_active",
      "fvg_active",
      "mtf_aligned"
    ],
    "description": "Tendance haussière, volatilité faible, phase de tendance. Les timeframes supérieurs sont alignés haussiers. À proximité : une FVG haussier actif (non testé) sous le prix (1,15182–1,15200) ; une FVG haussier actif (non testé) sous le prix (1,15081–1,15087). Structure : BOS haussier confirmé (1,15193). Un retest de cassure (BOS) est en cours (1,15193).",
    "description_source": "engine_template"
  }
};

export const SAMPLE_READING_XAU_D1: MarketReading = {
  "schema_version": "2.0.0",
  "header": {
    "instrument": "XAUUSD",
    "timeframe": "D1",
    "candle_close_ts": "2026-07-31T00:00:00Z",
    "close_price": 4111.96,
    "analysis_window_bars": 499
  },
  "structure": {
    "current_bos": null,
    "current_choch": null,
    "order_blocks": [
      {
        "id": "OB_bullish_20250905000000",
        "direction": "bullish",
        "level_high": 3564.19,
        "level_low": 3511.45,
        "importance": "high",
        "status": "active",
        "created_at": "2025-09-05T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20250919000000",
        "direction": "bullish",
        "level_high": 3672.9,
        "level_low": 3627.78,
        "importance": "high",
        "status": "active",
        "created_at": "2025-09-19T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260605000000",
        "direction": "bearish",
        "level_high": 4515.39,
        "level_low": 4424.02,
        "importance": "high",
        "status": "active",
        "created_at": "2026-06-05T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20250409000000",
        "direction": "bullish",
        "level_high": 3022.73,
        "level_low": 2974.73,
        "importance": "high",
        "status": "active",
        "created_at": "2025-04-09T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20250130000000",
        "direction": "bullish",
        "level_high": 2766.2,
        "level_low": 2744.76,
        "importance": "medium",
        "status": "active",
        "created_at": "2025-01-30T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20241118000000",
        "direction": "bullish",
        "level_high": 2576.05,
        "level_low": 2554.58,
        "importance": "medium",
        "status": "active",
        "created_at": "2024-11-18T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260129000000",
        "direction": "bearish",
        "level_high": 5418.95,
        "level_low": 5157.31,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-01-29T00:00:00Z",
        "tested": true,
        "mitigated_at": "2026-01-30T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20250303000000",
        "direction": "bullish",
        "level_high": 2885.05,
        "level_low": 2832.57,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2025-03-03T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-03-04T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20250207000000",
        "direction": "bullish",
        "level_high": 2873.28,
        "level_low": 2834.1,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2025-02-07T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-02-10T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260723000000",
        "direction": "bearish",
        "level_high": 4166.0,
        "level_low": 4076.55,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-23T00:00:00Z",
        "tested": true,
        "mitigated_at": "2026-07-24T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20250107000000",
        "direction": "bullish",
        "level_high": 2649.45,
        "level_low": 2614.45,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2025-01-07T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-01-08T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260601000000",
        "direction": "bearish",
        "level_high": 4595.18,
        "level_low": 4488.5,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-01T00:00:00Z",
        "tested": true,
        "mitigated_at": "2026-06-02T00:00:00Z",
        "user_flagged": false
      }
    ],
    "fair_value_gaps": [
      {
        "id": "FVG_bullish_20250410000000",
        "direction": "bullish",
        "level_high": 3071.36,
        "level_low": 3022.73,
        "status": "active",
        "created_at": "2025-04-10T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250313000000",
        "direction": "bullish",
        "level_high": 2932.99,
        "level_low": 2922.03,
        "status": "active",
        "created_at": "2025-03-13T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250829000000",
        "direction": "bullish",
        "level_high": 3404.36,
        "level_low": 3398.81,
        "status": "active",
        "created_at": "2025-08-29T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260313000000",
        "direction": "bearish",
        "level_high": 5149.28,
        "level_low": 5128.53,
        "status": "active",
        "created_at": "2026-03-13T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260515000000",
        "direction": "bearish",
        "level_high": 4669.45,
        "level_low": 4665.28,
        "status": "active",
        "created_at": "2026-05-15T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250411000000",
        "direction": "bullish",
        "level_high": 3176.0,
        "level_low": 3099.6,
        "status": "partially_filled",
        "created_at": "2025-04-11T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-05-14T00:00:00Z",
        "fill_level": 3120.78,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250314000000",
        "direction": "bullish",
        "level_high": 2978.45,
        "level_low": 2940.63,
        "status": "partially_filled",
        "created_at": "2025-03-14T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-04-07T00:00:00Z",
        "fill_level": 2956.26,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250122000000",
        "direction": "bullish",
        "level_high": 2741.1,
        "level_low": 2713.76,
        "status": "partially_filled",
        "created_at": "2025-01-22T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-01-23T00:00:00Z",
        "fill_level": 2730.48,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250903000000",
        "direction": "bullish",
        "level_high": 3526.3,
        "level_low": 3489.81,
        "status": "partially_filled",
        "created_at": "2025-09-03T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-09-04T00:00:00Z",
        "fill_level": 3511.45,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250131000000",
        "direction": "bullish",
        "level_high": 2791.02,
        "level_low": 2766.2,
        "status": "partially_filled",
        "created_at": "2025-01-31T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-02-03T00:00:00Z",
        "fill_level": 2772.17,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260319000000",
        "direction": "bearish",
        "level_high": 4973.51,
        "level_low": 4866.95,
        "status": "partially_filled",
        "created_at": "2026-03-19T00:00:00Z",
        "tested": true,
        "mitigated_at": "2026-04-15T00:00:00Z",
        "fill_level": 4889.64,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20250116000000",
        "direction": "bullish",
        "level_high": 2690.03,
        "level_low": 2678.38,
        "status": "partially_filled",
        "created_at": "2025-01-16T00:00:00Z",
        "tested": true,
        "mitigated_at": "2025-01-20T00:00:00Z",
        "fill_level": 2689.26,
        "user_flagged": false
      }
    ],
    "bos_events": [
      {
        "direction": "bearish",
        "level": 4023.74,
        "broken_at": "2026-06-24T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 26
      },
      {
        "direction": "bearish",
        "level": 4098.53,
        "broken_at": "2026-06-10T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 36
      },
      {
        "direction": "bullish",
        "level": 4642.91,
        "broken_at": "2026-01-19T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 137
      },
      {
        "direction": "bullish",
        "level": 4549.92,
        "broken_at": "2026-01-12T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 142
      },
      {
        "direction": "bullish",
        "level": 4381.53,
        "broken_at": "2025-12-22T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 155
      },
      {
        "direction": "bullish",
        "level": 4059.25,
        "broken_at": "2025-10-13T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 205
      },
      {
        "direction": "bullish",
        "level": 3791.18,
        "broken_at": "2025-09-29T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 215
      },
      {
        "direction": "bullish",
        "level": 3707.42,
        "broken_at": "2025-09-22T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 220
      },
      {
        "direction": "bullish",
        "level": 3674.12,
        "broken_at": "2025-09-15T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 225
      },
      {
        "direction": "bullish",
        "level": 3499.98,
        "broken_at": "2025-09-02T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 234
      },
      {
        "direction": "bullish",
        "level": 3167.73,
        "broken_at": "2025-04-10T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 336
      },
      {
        "direction": "bearish",
        "level": 2999.55,
        "broken_at": "2025-04-07T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 339
      },
      {
        "direction": "bullish",
        "level": 3057.26,
        "broken_at": "2025-03-28T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 345
      },
      {
        "direction": "bullish",
        "level": 2942.58,
        "broken_at": "2025-02-24T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 369
      },
      {
        "direction": "bullish",
        "level": 2790.09,
        "broken_at": "2025-01-30T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 386
      },
      {
        "direction": "bearish",
        "level": 2708.78,
        "broken_at": "2024-11-06T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 445
      },
      {
        "direction": "bullish",
        "level": 2758.47,
        "broken_at": "2024-10-29T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 451
      }
    ],
    "choch_events": [
      {
        "direction": "bearish",
        "level": 4098.53,
        "broken_at": "2026-06-10T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 36
      },
      {
        "direction": "bullish",
        "level": 3167.73,
        "broken_at": "2025-04-10T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 336
      },
      {
        "direction": "bearish",
        "level": 2999.55,
        "broken_at": "2025-04-07T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 339
      },
      {
        "direction": "bullish",
        "level": 2790.09,
        "broken_at": "2025-01-30T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 386
      },
      {
        "direction": "bearish",
        "level": 2708.78,
        "broken_at": "2024-11-06T00:00:00Z",
        "validation_status": "confirmed",
        "bars_ago": 445
      }
    ],
    "liquidity_pools": [
      {
        "id": "LIQ_bsl_range_high_20260202000000",
        "side": "bsl",
        "kind": "range_high",
        "level": 5598.03,
        "touches": 1,
        "is_external": true,
        "status": "intact",
        "created_at": "2026-02-02T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_range_low_20251030000000",
        "side": "ssl",
        "kind": "range_low",
        "level": 3886.62,
        "touches": 1,
        "is_external": true,
        "status": "intact",
        "created_at": "2025-10-30T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260511000000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4773.42,
        "touches": 2,
        "is_external": false,
        "status": "intact",
        "created_at": "2026-05-11T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260626000000",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 3958.96,
        "touches": 2,
        "is_external": false,
        "status": "swept",
        "created_at": "2026-06-26T00:00:00Z",
        "swept_at": "2026-06-30T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20251125000000",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 4022.61,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2025-11-25T00:00:00Z",
        "broken_at": "2026-06-24T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260501000000",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 4500.98,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-05-01T00:00:00Z",
        "swept_at": "2026-05-18T00:00:00Z",
        "broken_at": "2026-05-19T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260112000000",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 4402.14,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-01-12T00:00:00Z",
        "swept_at": "2026-03-23T00:00:00Z",
        "broken_at": "2026-03-26T00:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20251203000000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4264.63,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2025-12-03T00:00:00Z",
        "broken_at": "2025-12-11T00:00:00Z",
        "user_flagged": false
      }
    ]
  },
  "regime": {
    "trend": "bearish",
    "volatility_observed": "normal",
    "market_phase": "trend",
    "mtf_confluence": {},
    "volatility_detail": {
      "recent_avg": 93.11428571428549,
      "baseline_avg": 100.97100000000003,
      "ratio": 0.9221884077040483,
      "recent_n": 7,
      "baseline_n": 20,
      "threshold_low": 0.7,
      "threshold_high": 1.3
    },
    "trend_reference": {
      "kind": "choch",
      "direction": "bearish",
      "level": 4098.53,
      "broken_at": "2026-06-10T00:00:00Z",
      "bars_ago": 36
    }
  },
  "events": {
    "news_upcoming": [],
    "news_just_published": [
      {
        "event": "Core CPI Flash Estimate y/y",
        "published_at": "2026-07-31T09:00:00Z",
        "forecast": 2.4,
        "previous": 2.4,
        "currency": "EUR",
        "impact": "medium",
        "potential_effect_description": "Core CPI Flash Estimate y/y (EUR) — impact moyen, publié il y a 13h30.",
        "event_id": "42b9b12e27c92ab0"
      },
      {
        "event": "CPI Flash Estimate y/y",
        "published_at": "2026-07-31T09:00:00Z",
        "forecast": 2.9,
        "previous": 2.8,
        "currency": "EUR",
        "impact": "medium",
        "potential_effect_description": "CPI Flash Estimate y/y (EUR) — impact moyen, publié il y a 13h30.",
        "event_id": "73e469d41ba3b163"
      },
      {
        "event": "Employment Cost Index q/q",
        "published_at": "2026-07-31T12:30:00Z",
        "forecast": 0.8,
        "previous": 0.9,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Employment Cost Index q/q (USD) — impact moyen, publié il y a 10h.",
        "event_id": "def9226045ff5448"
      },
      {
        "event": "Revised UoM Consumer Sentiment",
        "published_at": "2026-07-31T14:00:00Z",
        "forecast": 53.9,
        "previous": 54.4,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Revised UoM Consumer Sentiment (USD) — impact moyen, publié il y a 8h30.",
        "event_id": "65755f3ddb3aca87"
      },
      {
        "event": "Revised UoM Inflation Expectations",
        "published_at": "2026-07-31T14:00:00Z",
        "previous": 4.2,
        "currency": "USD",
        "impact": "medium",
        "potential_effect_description": "Revised UoM Inflation Expectations (USD) — impact moyen, publié il y a 8h30.",
        "event_id": "4ac44cb1b05e7dd7"
      }
    ],
    "technical_triggers_recent": []
  },
  "conditions": {
    "tags": [
      "trend_bearish",
      "volatility_normal",
      "phase_trend",
      "ob_active",
      "fvg_active"
    ],
    "description": "Tendance baissière, volatilité normale, phase de tendance. Le prix évolue près d'un Order Block baissier mitigé (déjà testé) autour du prix (4 076,55–4 166,00).",
    "description_source": "engine_template"
  }
};

export const SAMPLE_READING_XAU_M15_SPARSE: MarketReading = {
  "schema_version": "2.0.0",
  "header": {
    "instrument": "XAUUSD",
    "timeframe": "M15",
    "candle_close_ts": "2026-07-04T18:00:00Z",
    "close_price": 4174.89556
  },
  "structure": {
    "current_bos": null,
    "current_choch": null,
    "order_blocks": [
      {
        "id": "OB_bullish_20260701131500",
        "direction": "bullish",
        "level_high": 4025.33671,
        "level_low": 4012.7717,
        "importance": "high",
        "status": "active",
        "created_at": "2026-07-01T13:15:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260703004500",
        "direction": "bullish",
        "level_high": 4139.24417,
        "level_low": 4133.51761,
        "importance": "high",
        "status": "active",
        "created_at": "2026-07-03T00:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260701103000",
        "direction": "bullish",
        "level_high": 3986.32317,
        "level_low": 3981.79039,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-07-01T10:30:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260703161500",
        "direction": "bullish",
        "level_high": 4165.45174,
        "level_low": 4163.71737,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-07-03T16:15:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bearish_20260703114500",
        "direction": "bearish",
        "level_high": 4185.67661,
        "level_low": 4183.0044,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-07-03T11:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260702000000",
        "direction": "bullish",
        "level_high": 4036.81576,
        "level_low": 4034.04736,
        "importance": "medium",
        "status": "active",
        "created_at": "2026-07-02T00:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260702164500",
        "direction": "bullish",
        "level_high": 4117.54462,
        "level_low": 4100.37723,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-02T16:45:00Z",
        "tested": true,
        "mitigated_at": "2026-07-02T17:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260702021500",
        "direction": "bullish",
        "level_high": 4052.62785,
        "level_low": 4041.52849,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-02T02:15:00Z",
        "tested": true,
        "mitigated_at": "2026-07-02T02:30:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260702004500",
        "direction": "bullish",
        "level_high": 4047.08837,
        "level_low": 4038.44601,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-02T00:45:00Z",
        "tested": true,
        "mitigated_at": "2026-07-02T01:30:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260701074500",
        "direction": "bullish",
        "level_high": 3970.45978,
        "level_low": 3961.18043,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-01T07:45:00Z",
        "tested": true,
        "mitigated_at": "2026-07-01T08:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260630024500",
        "direction": "bullish",
        "level_high": 3963.84969,
        "level_low": 3950.6432,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-06-30T02:45:00Z",
        "tested": true,
        "mitigated_at": "2026-06-30T03:00:00Z",
        "user_flagged": false
      },
      {
        "id": "OB_bullish_20260701233000",
        "direction": "bullish",
        "level_high": 4040.19591,
        "level_low": 4034.16858,
        "importance": "high",
        "status": "mitigated",
        "created_at": "2026-07-01T23:30:00Z",
        "tested": true,
        "mitigated_at": "2026-07-01T23:45:00Z",
        "user_flagged": false
      }
    ],
    "fair_value_gaps": [
      {
        "id": "FVG_bullish_20260701111500",
        "direction": "bullish",
        "level_high": 4012.24043,
        "level_low": 3998.1514,
        "status": "active",
        "created_at": "2026-07-01T11:15:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260703010000",
        "direction": "bullish",
        "level_high": 4145.21895,
        "level_low": 4139.24417,
        "status": "active",
        "created_at": "2026-07-03T01:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260701110000",
        "direction": "bullish",
        "level_high": 3997.91287,
        "level_low": 3994.40783,
        "status": "active",
        "created_at": "2026-07-01T11:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260702200000",
        "direction": "bullish",
        "level_high": 4117.22954,
        "level_low": 4114.54905,
        "status": "active",
        "created_at": "2026-07-02T20:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260703163000",
        "direction": "bullish",
        "level_high": 4166.57876,
        "level_low": 4165.45174,
        "status": "active",
        "created_at": "2026-07-03T16:30:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260701094500",
        "direction": "bullish",
        "level_high": 3980.69027,
        "level_low": 3979.9411,
        "status": "active",
        "created_at": "2026-07-01T09:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260701104500",
        "direction": "bullish",
        "level_high": 3986.92289,
        "level_low": 3986.32317,
        "status": "active",
        "created_at": "2026-07-01T10:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260701093000",
        "direction": "bullish",
        "level_high": 3976.96218,
        "level_low": 3976.61749,
        "status": "active",
        "created_at": "2026-07-01T09:30:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260703164500",
        "direction": "bullish",
        "level_high": 4168.50799,
        "level_low": 4168.27982,
        "status": "active",
        "created_at": "2026-07-03T16:45:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bearish_20260703120000",
        "direction": "bearish",
        "level_high": 4183.0044,
        "level_low": 4182.87531,
        "status": "active",
        "created_at": "2026-07-03T12:00:00Z",
        "tested": false,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260702124500",
        "direction": "bullish",
        "level_high": 4117.29122,
        "level_low": 4069.50718,
        "status": "partially_filled",
        "created_at": "2026-07-02T12:45:00Z",
        "tested": true,
        "mitigated_at": "2026-07-02T13:00:00Z",
        "fill_level": 4100.37723,
        "user_flagged": false
      },
      {
        "id": "FVG_bullish_20260703011500",
        "direction": "bullish",
        "level_high": 4173.7969,
        "level_low": 4150.23864,
        "status": "partially_filled",
        "created_at": "2026-07-03T01:15:00Z",
        "tested": true,
        "mitigated_at": "2026-07-03T04:00:00Z",
        "fill_level": 4156.27598,
        "user_flagged": false
      }
    ],
    "bos_events": [
      {
        "direction": "bullish",
        "level": 4115.77285,
        "broken_at": "2026-07-02T12:30:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bullish",
        "level": 4036.10385,
        "broken_at": "2026-07-01T13:15:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bullish",
        "level": 3986.36282,
        "broken_at": "2026-07-01T10:30:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bullish",
        "level": 3979.15998,
        "broken_at": "2026-07-01T08:15:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bearish",
        "level": 3963.53547,
        "broken_at": "2026-07-01T07:00:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bearish",
        "level": 3970.45978,
        "broken_at": "2026-07-01T06:00:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bearish",
        "level": 4009.30158,
        "broken_at": "2026-06-30T20:45:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bullish",
        "level": 4036.9413,
        "broken_at": "2026-06-30T14:00:00Z",
        "validation_status": "confirmed"
      }
    ],
    "choch_events": [
      {
        "direction": "bullish",
        "level": 3979.15998,
        "broken_at": "2026-07-01T08:15:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bearish",
        "level": 4009.30158,
        "broken_at": "2026-06-30T20:45:00Z",
        "validation_status": "confirmed"
      },
      {
        "direction": "bullish",
        "level": 4021.87902,
        "broken_at": "2026-06-30T06:30:00Z",
        "validation_status": "confirmed"
      }
    ],
    "liquidity_pools": [
      {
        "id": "LIQ_bsl_range_high_20260703020000",
        "side": "bsl",
        "kind": "range_high",
        "level": 4195.33479,
        "touches": 1,
        "is_external": true,
        "status": "intact",
        "created_at": "2026-07-03T02:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_range_low_20260702170000",
        "side": "ssl",
        "kind": "range_low",
        "level": 4100.37723,
        "touches": 1,
        "is_external": true,
        "status": "intact",
        "created_at": "2026-07-02T17:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260703223000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4175.10336,
        "touches": 14,
        "is_external": false,
        "status": "intact",
        "created_at": "2026-07-03T22:30:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260703221500",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 4174.8424,
        "touches": 56,
        "is_external": false,
        "status": "intact",
        "created_at": "2026-07-03T22:15:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_ssl_equal_lows_20260703181500",
        "side": "ssl",
        "kind": "equal_lows",
        "level": 4174.58316,
        "touches": 3,
        "is_external": false,
        "status": "intact",
        "created_at": "2026-07-03T18:15:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260703030000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4186.90337,
        "touches": 2,
        "is_external": false,
        "status": "intact",
        "created_at": "2026-07-03T03:00:00Z",
        "user_flagged": false
      },
      {
        "id": "LIQ_bsl_equal_highs_20260703153000",
        "side": "bsl",
        "kind": "equal_highs",
        "level": 4174.31959,
        "touches": 2,
        "is_external": false,
        "status": "broken",
        "created_at": "2026-07-03T15:30:00Z",
        "broken_at": "2026-07-03T16:45:00Z",
        "user_flagged": false
      }
    ]
  },
  "regime": {
    "trend": "bullish",
    "volatility_observed": "low",
    "market_phase": "trend",
    "mtf_confluence": {
      "h1": "bullish",
      "h4": "bearish"
    }
  },
  "events": {
    "news_upcoming": [],
    "news_just_published": [],
    "technical_triggers_recent": []
  },
  "conditions": {
    "tags": [
      "trend_bullish",
      "volatility_low",
      "phase_trend",
      "ob_active",
      "fvg_active",
      "mtf_divergent"
    ],
    "description": "Le prix se situe à 4 174,90 en tendance haussière avec une volatilité faible, confirmé en timeframe H1, mais le timeframe H4 affiche une orientation baissière divergente. Deux zones FVG non testées encadrent le prix : un FVG haussier actif entre 4 168,28–4 168,51 en dessous, et un FVG baissier actif entre 4 182,88–4 183,00 au-dessus, ce dernier s'opposant à la tendance haussière actuelle. Un OB baissier actif se prolonge entre 4 183,00–4 185,68, également au-dessus du prix. Cette configuration expose un contraste : la tendance H1 haussière coexiste avec une pression baissière en timeframe supérieur et des structures baissières confirmées en attente de test.",
    "description_source": "engine_template"
  }
};

export const SAMPLE_READINGS: readonly MarketReading[] = [
  SAMPLE_READING_XAU_H4,
  SAMPLE_READING_EUR_M15,
  SAMPLE_READING_XAU_D1,
  SAMPLE_READING_XAU_M15_SPARSE,
];
