"""MarketReadingAssembler — lazy on-demand generation of MarketReading objects.

Section 3.1 of the V2 architecture doc ("Moteur hybride lazy puis continu").
Chantier 2 implements the **lazy** path only — the recurring scheduler job
(continu after first access, auto-stop after 24h) is Chantier 3.

Lazy flow per get_or_generate():
  1. Compute expected last-candle-close timestamp for (instrument, timeframe).
  2. Read latest stored MarketReading for that pair.
  3. If it matches the expected close → return it (cache hit), still mark
     the combination as active.
  4. Otherwise: fetch candles via data_provider, persist into candles_store,
     run the SMC pipeline, build the structure/regime/events/conditions,
     persist via readings_store, mark active, return.

The SMC pipeline (smc_features extraction + optional confluence) is injectable
via the ``smc_pipeline`` callable so the assembler stays testable without
needing the heavy SmartMoneyEngine / ConfluenceDetector classes at unit-test
time. The default implementation lazily wires the real engine.

The Haiku description engine is also injectable (Étape 5). When absent, the
assembler uses the template fallback from market_reading_mappers.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timedelta, timezone
from typing import Any, Callable, Mapping, Optional, Sequence, Tuple

# Version of the reading-derivation LOGIC (SMC mapping / lifecycle rules).
# The store keeps a computed MarketReading payload keyed by candle_close_ts; the
# state of OB/FVG/liquidity is BAKED INTO that JSON at generation time. A pure
# logic fix (e.g. LQ-D1: liquidity judged from first_k, time-aware clustering)
# therefore stays invisible on a still-matching cache — the screen keeps serving
# the old baked-in state until a new candle forces a rebuild. Bumping this
# constant marks every payload generated by older logic as stale, so the next
# read rebuilds it with the current rules. BUMP IT whenever a change alters the
# computed state of an already-storable reading.
READING_LOGIC_VERSION = 3  # MT-D1: per-timeframe analysis window + uncapped event journal

# Env kill switch (LQ-D1): masks ALL external-liquidity pockets at the serve
# layer — cache-hit AND fresh build — in one reversible value. Data is untouched
# in the store; clearing the variable brings everything back. Set to disable
# liquidity display instantly while a state fix is being rolled out.
_LIQUIDITY_DISABLED_ENV = "SENTINEL_LIQUIDITY_DISABLED"


def _liquidity_display_disabled() -> bool:
    return os.environ.get(_LIQUIDITY_DISABLED_ENV, "").strip().lower() in (
        "1", "true", "yes", "on",
    )

from src.intelligence.market_reading_mappers import (
    candles_to_regime,
    confluence_signal_to_structure,
    empty_events,
    tags_and_description,
)
from src.intelligence.market_reading_schema import (
    MarketReading,
    MarketReadingConditions,
    MarketReadingEvents,
    MarketReadingHeader,
)
from src.intelligence.market_calendar import (
    compute_market_status,
    market_aware_expected_close,
)
from src.intelligence.narrated_reading import build_reading_facts, render_template
from src.intelligence.provider_snapshot import snapshot_provider_response

logger = logging.getLogger(__name__)


# Timeframe minute durations — derived from the single timeframe registry (TF-1),
# not a second copy. Kept under the same name so existing importers are unchanged.
from src.intelligence import timeframe_registry as _tfreg
from src.intelligence import lookback_config

_TIMEFRAME_MINUTES: dict[str, int] = _tfreg.minutes_map()


def expected_last_candle_close(timeframe: str, now: datetime) -> datetime:
    """Return the close timestamp of the most recent fully-closed candle.

    By convention here, candle_close_ts is the boundary at which a candle
    completes (e.g. M15 candle 13:45-14:00 closes at 14:00:00Z). The "last
    fully closed" candle's close ts is the most recent boundary that has
    elapsed at ``now``.
    """
    tf_key = timeframe.upper()
    if tf_key not in _TIMEFRAME_MINUTES:
        raise ValueError(
            f"Unsupported timeframe: {timeframe!r}. "
            f"Supported: {sorted(_TIMEFRAME_MINUTES)}"
        )
    minutes = _TIMEFRAME_MINUTES[tf_key]
    ts = now.astimezone(timezone.utc) if now.tzinfo else now.replace(tzinfo=timezone.utc)
    epoch_minutes = int(ts.timestamp() // 60)
    last_boundary_minutes = (epoch_minutes // minutes) * minutes
    return datetime.fromtimestamp(last_boundary_minutes * 60, tz=timezone.utc)


def drop_unclosed_candles(
    candles: Sequence[Any], timeframe: str, expected_close: datetime
) -> list[Any]:
    """Keep only the bars fully closed at ``expected_close``.

    Twelve Data labels bars by OPEN time and includes the still-forming bar in
    its response. Analysing that bar makes every detector repaint (audit
    DETECTION_QUALITY_REVIEW_2026_06_12 §T3): the same OB was published twice
    under two ids, and readings were not reproducible from final candles.

    A bar opened at ``ts`` is closed iff ``ts + timeframe <= expected_close``.
    This also drops any future-labelled bar (defence-in-depth against the §T2
    timezone mislabelling). Naive timestamps are treated as UTC, matching the
    provider parse and the candles cache convention.
    """
    minutes = _TIMEFRAME_MINUTES[timeframe.upper()]
    span = timedelta(minutes=minutes)
    out: list[Any] = []
    for candle in candles:
        ts = candle.ts
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        if ts + span <= expected_close:
            out.append(candle)
    return out


SmcPipelineFn = Callable[[Sequence[Any]], Tuple[dict[str, float], Optional[Any]]]


def build_enriched_frame(candles: Sequence[Any]) -> Tuple[Any, Any]:
    """Build the SMC-enriched frame from a candle list — THE shared engine run.

    Returns ``(enriched_df, engine_config)``. Extracted from
    ``_default_smc_pipeline`` (which still flows through here) so the OB
    rejection diagnostics analyse EXACTLY the frame/config the readings are
    built from — same DataFrame construction, same default SMCConfig, same
    ``analyze`` flags. Heavy imports are local so unit tests with mocks pay no
    import cost.
    """
    import pandas as pd

    from src.intelligence.smart_money import SmartMoneyEngine

    df = pd.DataFrame(
        [
            {
                "open": float(c.open),
                "high": float(c.high),
                "low": float(c.low),
                "close": float(c.close),
                "volume": float(getattr(c, "volume", 0.0)),
            }
            for c in candles
        ],
        index=[c.ts for c in candles],
    )
    df.index.name = "ts"

    engine = SmartMoneyEngine(data=df, config={}, verbose=False)
    # compute_divergence=False: the MarketReading mapper does not consume the
    # RSI divergence column, so we skip its O(n·k) pass on every reading (D2-9).
    enriched = engine.analyze(compute_divergence=False)
    return enriched, engine.config


def _default_smc_pipeline(candles: Sequence[Any]) -> Tuple[dict[str, float], Optional[Any]]:
    """Default SMC pipeline — runs SmartMoneyEngine on the candle list.

    Returns ``(smc_features, confluence_signal=None)`` because Chantier 2
    does not wire ConfluenceDetector by default (scoring is for the legacy
    InsightSignalV2 flow; MarketReading describes state, not setups).
    Callers wanting a ConfluenceSignal can inject a custom pipeline.
    """
    if not candles:
        return {}, None

    import pandas as pd

    enriched, engine_config = build_enriched_frame(candles)
    last_row = enriched.iloc[-1].to_dict()

    smc_features: dict[str, float] = {}
    for k, v in last_row.items():
        if isinstance(v, bool):  # bool is a subclass of int — exclude
            smc_features[str(k)] = 1.0 if v else 0.0
        elif isinstance(v, (int, float)) and not pd.isna(v):
            smc_features[str(k)] = float(v)

    # Merge the REAL structural levels (BOS break level forward-filled, real
    # OB zone, real FVG bounds) so the structure mapper publishes them instead
    # of price ± ATR proxies (audit findings F1/F2/F3). Glue, not engine logic.
    from src.intelligence.market_reading_mappers import (
        collect_liquidity_pools,
        collect_structure_events,
        collect_zones,
        realized_levels,
    )
    last_idx = len(enriched) - 1
    smc_features.update(realized_levels(enriched, idx=last_idx))
    # Multi-zone registry: surface ALL still-relevant OB/FVG zones the engine
    # computed over the window, not just the last bar (audit §T1). Carried under
    # a reserved key the structure mapper consumes; never persisted.
    smc_features["_zones"] = collect_zones(enriched, idx=last_idx)
    # Discrete BOS/CHOCH break-event history over the window (twin of _zones):
    # fixes the "sous-surfaçage" where only the last-bar break ever surfaced
    # (audit 2026-06-16). Reserved key consumed by the structure mapper.
    smc_features["_structure_events"] = collect_structure_events(enriched, idx=last_idx)
    # External liquidity pockets (EQH/EQL + range extremes) with intact/swept/
    # broken state. Reuses the engine's swing fractals; thresholds come from the
    # validated SMCConfig (single source of truth). Reserved key, never persisted.
    cfg = engine_config
    smc_features["_liquidity"] = collect_liquidity_pools(
        enriched,
        idx=last_idx,
        eq_tolerance_atr=cfg.EQ_TOLERANCE_ATR,
        eq_tolerance_pips_floor=cfg.EQ_TOLERANCE_PIPS_FLOOR,
        eq_min_touches=cfg.EQ_MIN_TOUCHES,
        lookback=cfg.LIQ_LOOKBACK,
    )
    return smc_features, None


class MarketReadingAssembler:
    """Lazy on-demand assembler for MarketReading objects.

    Lifecycle: one instance per process (or per worker). Thread-safety is
    inherited from the underlying stores (RLock).
    """

    # Indicator-grade context windows. Widened 2026-06-15 (was lookback=200,
    # news 240/60 min) so the product shows real history + a multi-day economic
    # calendar, not a 4h keyhole. All overridable via env in the bootstrap.
    DEFAULT_LOOKBACK = 500
    DEFAULT_NEWS_LOOKAHEAD_MIN = 4320   # 3 days — captures FOMC/NFP ahead
    DEFAULT_NEWS_LOOKBACK_MIN = 1440    # 24h — what moved the market today

    def __init__(
        self,
        data_provider: Any,
        readings_store: Any,
        candles_store: Any,
        smc_pipeline: Optional[SmcPipelineFn] = None,
        description_engine: Optional[Any] = None,
        news_pipeline: Optional[Any] = None,
        lookback: int = DEFAULT_LOOKBACK,
        mtf_provider: Optional[Callable[[str, str], Mapping[str, Sequence[Any]]]] = None,
        clock: Callable[[], datetime] = lambda: datetime.now(timezone.utc),
        news_lookahead_min: int = DEFAULT_NEWS_LOOKAHEAD_MIN,
        news_lookback_min: int = DEFAULT_NEWS_LOOKBACK_MIN,
    ) -> None:
        self._data_provider = data_provider
        self._readings_store = readings_store
        self._candles_store = candles_store
        self._smc_pipeline: SmcPipelineFn = smc_pipeline or _default_smc_pipeline
        self._description_engine = description_engine
        self._news_pipeline = news_pipeline
        self._lookback = lookback
        self._mtf_provider = mtf_provider
        self._clock = clock
        self._news_lookahead_min = news_lookahead_min
        self._news_lookback_min = news_lookback_min

    # ------------------------------------------------------------------ #
    # Public accessors (used by the Chantier 3 scheduler / bootstrap)
    # ------------------------------------------------------------------ #
    @property
    def readings_store(self) -> Any:
        return self._readings_store

    @property
    def candles_store(self) -> Any:
        return self._candles_store

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #
    def get_or_generate(self, instrument: str, timeframe: str) -> MarketReading:
        """Return the current MarketReading for (instrument, timeframe).

        Lazy: re-uses the stored payload if it matches the expected last
        candle close. Otherwise re-generates end-to-end. Always marks the
        combination as active (Section 3.3 of architecture doc — hybrid
        scheduler state for Chantier 3).

        MC-1 emission lock: ``expected_close`` is **market-aware** — while the
        market is closed (weekend / holiday / daily break) it freezes at the
        last traded candle, so the stored reading keeps matching, nothing is
        re-fetched from Twelve Data and no "new" structure is re-emitted. This
        is the server-side verrou, not a display filter: the reading is never
        rebuilt without a genuinely new closed candle.
        """
        expected_close = market_aware_expected_close(instrument, timeframe, self._clock())

        existing = self._readings_store.get_latest_reading(instrument, timeframe)
        if (
            existing is not None
            and existing.get("_logic_version") == READING_LOGIC_VERSION
            and self._payload_matches(existing, expected_close)
        ):
            self._readings_store.mark_combination_active(instrument, timeframe)
            return self._with_status(
                MarketReading.model_validate(existing), instrument, timeframe
            )

        reading = self._build_fresh(instrument, timeframe, expected_close)
        self._persist_reading(instrument, timeframe, expected_close, reading)
        self._readings_store.mark_combination_active(instrument, timeframe)
        return self._with_status(reading, instrument, timeframe)

    def _persist_reading(
        self,
        instrument: str,
        timeframe: str,
        candle_close_ts: datetime,
        reading: MarketReading,
    ) -> None:
        """Save a freshly built reading, stamped with the current logic version.

        The stamp lets :meth:`get_or_generate` detect a payload produced by older
        derivation logic and rebuild it, so a pure logic fix (LQ-D1) reaches the
        screen on the next read instead of staying frozen in the cache.
        """
        payload = reading.model_dump(mode="json")
        payload["_logic_version"] = READING_LOGIC_VERSION
        self._readings_store.save_reading(
            instrument, timeframe, candle_close_ts, payload
        )

    def _with_status(
        self, reading: MarketReading, instrument: str, timeframe: str
    ) -> MarketReading:
        """Attach the fresh market status to a reading WITHOUT persisting it.

        The stored payload never carries a status (it depends on ``now``); every
        response computes it from the calendar + the stored ``candle_close_ts``
        so the App badge, Scanner and agent all read the same server truth."""
        # LQ-D1 kill switch — single choke point both the cache-hit and the fresh
        # build pass through, so one env value masks liquidity on EVERY response
        # (including already-stored payloads) without touching the data.
        if _liquidity_display_disabled():
            reading.structure.liquidity_pools = []
        try:
            reading.market_status = self.market_status(instrument, timeframe).to_dict()
        except Exception:  # pragma: no cover — status must never break a reading
            logger.warning("market_status attach failed for %s/%s", instrument, timeframe)
        try:
            reading.reference_levels = self.reference_levels(instrument)
        except Exception:  # pragma: no cover — levels must never break a reading
            logger.warning("reference_levels attach failed for %s", instrument)
        return reading

    # Intraday source for the calendar reference levels, coarsest-first that
    # still covers the previous week with the assembler lookback: H1 (~4 weeks of
    # trading hours) gives hourly precision for opens and extremes; H4/M15 are
    # fallbacks. Independent of the displayed timeframe — the « day »/« week »
    # boundary is the MC-1 trading calendar, one definition (see reference_levels).
    _REFERENCE_SOURCE_TFS: tuple[str, ...] = ("H1", "H4", "M15")

    def reference_levels(self, instrument: str) -> Optional[dict]:
        """Fresh calendar reference levels for ``instrument`` (RG-1c).

        A pure cache read + arithmetic: aggregates the six levels over MC-1
        trading days/weeks from the intraday candles already cached. Returns
        ``None`` when no usable source series is cached (caller shows nothing)."""
        from src.intelligence.reference_levels import compute_reference_levels

        for tf in self._REFERENCE_SOURCE_TFS:
            candles = self._candles_store.get_last_n_candles(instrument, tf, self._lookback)
            if candles:
                return compute_reference_levels(instrument, candles, self._clock()).to_dict()
        return None

    def refresh_if_reopened(self, instrument: str, timeframe: str) -> bool:
        """Infrequent safety probe (MC-1): the market may reopen *before* the
        configured calendar time (e.g. an unforeseen holiday that turned out to
        be a trading day). Makes ONE Twelve Data call and rebuilds the reading
        **only if the provider actually returns a closed candle newer than the
        frozen one** — stamped with that real candle's close, never the wall
        clock. Returns True when it refreshed.

        Deliberately conservative: when the market-aware close has not advanced
        past the frozen close (the normal case for a still-closed market) it may
        still find no new data and leave everything frozen. The scheduler only
        calls this on holiday closures and at a low frequency, so a weekend
        makes zero outbound calls."""
        now = self._clock()
        clock_expected = expected_last_candle_close(timeframe, now)
        frozen = market_aware_expected_close(instrument, timeframe, now)
        if clock_expected <= frozen:
            return False

        raw = self._data_provider.fetch_candles(instrument, timeframe, self._lookback)
        candles = drop_unclosed_candles(raw, timeframe, clock_expected)
        if not candles:
            return False
        span = timedelta(minutes=_TIMEFRAME_MINUTES[timeframe.upper()])
        last_ts = candles[-1].ts
        if last_ts.tzinfo is None:
            last_ts = last_ts.replace(tzinfo=timezone.utc)
        actual_close = last_ts.astimezone(timezone.utc) + span

        stored = self.market_status(instrument, timeframe).last_close_ts
        if stored is not None and actual_close <= stored:
            return False  # provider has nothing newer — still closed, stay frozen

        reading = self._build_fresh(instrument, timeframe, actual_close, raw_candles=raw)
        self._persist_reading(instrument, timeframe, actual_close, reading)
        self._readings_store.mark_combination_active(instrument, timeframe)
        return True

    def market_status(self, instrument: str, timeframe: str):
        """Current :class:`MarketStatus` for (instrument, timeframe).

        Fact-first: the "last closed candle" is read from the stored reading's
        ``candle_close_ts`` (the real data), never from the wall clock. The
        calendar only names the reason and supplies the reopen time. A pure
        read — never fetches, never rebuilds, never mutates a store.
        """
        last_close_ts: Optional[datetime] = None
        existing = self._readings_store.get_latest_reading(instrument, timeframe)
        if isinstance(existing, Mapping):
            header = existing.get("header")
            if isinstance(header, Mapping):
                raw_ts = header.get("candle_close_ts")
                if raw_ts is not None:
                    try:
                        last_close_ts = (
                            raw_ts
                            if isinstance(raw_ts, datetime)
                            else datetime.fromisoformat(str(raw_ts).replace("Z", "+00:00"))
                        )
                    except ValueError:
                        last_close_ts = None
        return compute_market_status(instrument, timeframe, last_close_ts, self._clock())

    def warm_candles(self, instrument: str, timeframe: str) -> int:
        """Fetch + cache the CLOSED candles for (instrument, timeframe) WITHOUT
        building a reading — used to populate the D1/W1 reference series for the
        Régime « Niveaux de référence » tile, which the scheduler does not keep
        warm. No SMC pipeline, no readings-store write: pure candle cache fill.

        Idempotent + market-aware: refreshes only when the cache is empty or the
        newest cached candle lags the last candle that actually traded, so it
        makes at most one provider call per closed D1/W1 bar. Returns the number
        of candles now cached (0 on a fetch failure — caller degrades to 404)."""
        try:
            expected_close = market_aware_expected_close(instrument, timeframe, self._clock())
            existing = self._candles_store.get_last_n_candles(instrument, timeframe, 1)
            if existing:
                newest = existing[-1].ts
                if newest.tzinfo is None:
                    newest = newest.replace(tzinfo=timezone.utc)
                if newest >= expected_close:
                    return 1  # cache already has the last traded bar — no fetch
            raw = self._data_provider.fetch_candles(instrument, timeframe, self._lookback)
            candles = drop_unclosed_candles(raw, timeframe, expected_close)
            if candles:
                self._candles_store.upsert_candles(instrument, timeframe, candles)
            return len(candles)
        except Exception:  # pragma: no cover — defensive; caller degrades to 404
            logger.exception("warm_candles failed for %s/%s", instrument, timeframe)
            return 0

    def get_ob_diagnostic(
        self,
        instrument: str,
        timeframe: str,
        ts: Optional[Any] = None,
        price: Optional[float] = None,
    ) -> dict:
        """On-demand OB rejection diagnostic (mission 2026-07-02) — read-only.

        Explains why a given candle (referenced by timestamp or approximate
        price) is or is not an Order Block, by reading the engine's OWN
        decision path: same candle cache the readings populate, same
        ``build_enriched_frame`` run, then ``ob_diagnostics.diagnose_ob`` over
        the named detection criteria and the zone collector's reject records.
        Never mutates stores, never re-detects with different thresholds, and
        returns an honest ``unresolved``/``no_data`` status instead of guessing.
        """
        from src.intelligence.ob_diagnostics import diagnose_ob

        expected_close = market_aware_expected_close(instrument, timeframe, self._clock())
        raw = self._candles_store.get_last_n_candles(
            instrument, timeframe, self._lookback
        )
        candles = drop_unclosed_candles(raw, timeframe, expected_close)
        if not candles:
            return {
                "status": "no_data",
                "resolution": {"resolved": False, "reason": "no_data"},
                "instrument": instrument,
                "timeframe": timeframe,
                "note_fr": (
                    "aucune bougie en cache pour cette combinaison — ouvre "
                    "d'abord la lecture correspondante"
                ),
            }
        enriched, engine_config = build_enriched_frame(candles)
        diag = diagnose_ob(enriched, engine_config, ts=ts, price=price)
        diag["instrument"] = instrument
        diag["timeframe"] = timeframe
        return diag

    # ------------------------------------------------------------------ #
    # Internals
    # ------------------------------------------------------------------ #
    @staticmethod
    def _payload_matches(payload: Mapping[str, Any], expected_close: datetime) -> bool:
        header = payload.get("header") if isinstance(payload, Mapping) else None
        if not isinstance(header, Mapping):
            return False
        stored_ts = header.get("candle_close_ts")
        if stored_ts is None:
            return False
        try:
            parsed = (
                stored_ts
                if isinstance(stored_ts, datetime)
                else datetime.fromisoformat(str(stored_ts).replace("Z", "+00:00"))
            )
        except ValueError:
            return False
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed.astimezone(timezone.utc) == expected_close

    def _window_bars(self, timeframe: str) -> int:
        """Per-timeframe live analysis window (MT-D1 fix). Fast units get more
        recent history than the legacy fixed 500; slow units keep 500 via the
        floor. Falls back to the configured global lookback on an unknown unit."""
        try:
            return lookback_config.analysis_window_bars(timeframe)
        except Exception:
            return self._lookback

    def _build_fresh(
        self,
        instrument: str,
        timeframe: str,
        expected_close: datetime,
        raw_candles: Optional[Sequence[Any]] = None,
    ) -> MarketReading:
        if raw_candles is None:
            raw_candles = self._data_provider.fetch_candles(
                instrument, timeframe, self._window_bars(timeframe)
            )
        # Raw response snapshot BEFORE any filtering — the only way to replay
        # a reading bit-for-bit later (the feed revises forming bars; audit §T3
        # found a reading whose close_price existed in no stored final candle).
        snapshot_provider_response(
            instrument, timeframe, raw_candles, fetched_at=self._clock()
        )
        # The forming bar (and any future-labelled bar) never reaches the SMC
        # pipeline nor the cache: candle_close_ts promises closed-candle data,
        # and /api/candles documents "stops at the last fully-closed candle".
        candles = drop_unclosed_candles(raw_candles, timeframe, expected_close)
        if candles:
            try:
                self._candles_store.upsert_candles(instrument, timeframe, candles)
            except Exception as exc:  # pragma: no cover — defensive cache write
                logger.warning(
                    "candles_store.upsert_candles failed for %s/%s: %s",
                    instrument, timeframe, exc,
                )

        smc_features, confluence_signal = self._smc_pipeline(candles)
        current_price = float(candles[-1].close) if candles else 0.0

        # Honesty (DG-1 point 1): the header timestamp must name the LAST CANDLE
        # ACTUALLY ANALYSED — derived from the real data (candles[-1].ts + span),
        # never the wall-clock/calendar ``expected_close``. Otherwise a stalled
        # feed (e.g. provider quota) keeps advancing candle_close_ts on the clock
        # while the data underneath is frozen, and the "Données en retard"
        # detection (market_status compares expected vs this stamp) can never
        # fire — a lag stays silent. ``expected_close`` remains the CACHE-MATCH
        # target only. When the data is fresh the two are equal.
        span = timedelta(minutes=_TIMEFRAME_MINUTES[timeframe.upper()])
        if candles:
            last_ts = candles[-1].ts
            if last_ts.tzinfo is None:
                last_ts = last_ts.replace(tzinfo=timezone.utc)
            actual_close = last_ts.astimezone(timezone.utc) + span
        else:
            actual_close = expected_close

        structure = confluence_signal_to_structure(
            confluence_signal=confluence_signal,
            smc_features=smc_features,
            bar_ts=actual_close,
            current_price=current_price,
        )

        mtf_candles: Mapping[str, Sequence[Any]] = {}
        if self._mtf_provider is not None:
            try:
                mtf_candles = self._mtf_provider(instrument, timeframe) or {}
            except Exception as exc:  # pragma: no cover — defensive
                logger.warning("mtf_provider failed for %s/%s: %s", instrument, timeframe, exc)

        candle_dicts = [
            {
                "open": float(c.open),
                "high": float(c.high),
                "low": float(c.low),
                "close": float(c.close),
            }
            for c in candles
        ]
        regime = candles_to_regime(candle_dicts, mtf_candles_above=mtf_candles)

        events = self._build_events()

        tags, _ = tags_and_description(structure, regime)
        description, source = self._resolve_description(
            tags, regime, structure, current_price, instrument
        )

        header = MarketReadingHeader(
            instrument=instrument,
            timeframe=timeframe,
            candle_close_ts=actual_close,
            close_price=current_price,
            # Real number of bars actually analysed for this reading — the honest
            # « fenêtre » the front labels (MT-D1). May be < the target window when
            # the store/provider holds fewer bars.
            analysis_window_bars=len(candle_dicts),
        )
        conditions = MarketReadingConditions(
            tags=tags,
            description=description,
            description_source=source,
        )

        return MarketReading(
            header=header,
            structure=structure,
            regime=regime,
            events=events,
            conditions=conditions,
        )

    def _build_events(self) -> MarketReadingEvents:
        """Fill ``news_upcoming`` / ``news_just_published`` from the pipeline.

        Compat Chantier 2: when no news pipeline is wired, returns an empty
        events block (identical to ``empty_events()``). News timing is
        independent of candle cadence (architecture doc §3.6) so the wall
        clock is used as the reference ``now``. ``technical_triggers_recent``
        is left empty here — out of scope for Chantier 3.
        """
        if self._news_pipeline is None:
            return empty_events()
        now = self._clock()
        try:
            upcoming = self._news_pipeline.get_upcoming(
                currency_filter=["USD", "EUR"],
                lookahead_minutes=self._news_lookahead_min,
                now=now,
            )
            published = self._news_pipeline.get_just_published(
                currency_filter=["USD", "EUR"],
                lookback_minutes=self._news_lookback_min,
                now=now,
            )
        except Exception as exc:  # pragma: no cover — defensive
            logger.warning("news_pipeline failed: %s — emitting empty events", exc)
            return empty_events()
        return MarketReadingEvents(
            news_upcoming=upcoming,
            news_just_published=published,
        )

    def _resolve_description(
        self,
        tags: list[str],
        regime: Any,
        structure: Any,
        price: float,
        instrument: str,
    ) -> tuple[str, str]:
        """Narrated reading, anchored to the engine facts.

        Uses the Haiku engine if injected (it validates against the same facts and
        falls back internally), else the deterministic template — so the panel is
        always factual and always present. The template is also the safety net
        when the engine raises before returning.
        """
        facts = build_reading_facts(structure, regime, price, instrument)
        fallback = render_template(facts)
        if self._description_engine is None:
            return fallback, "template_fallback"
        try:
            description, source = self._description_engine.generate(
                tags, regime, structure, price, instrument
            )
            return description, source
        except Exception as exc:  # pragma: no cover — defensive
            logger.warning("description_engine.generate failed: %s — using template", exc)
            return fallback, "template_fallback"


# ---------------------------------------------------------------------------
# Multi-timeframe bias provider (cache-only)
# ---------------------------------------------------------------------------

# Timeframe ladder (low → high) and the MTF key each maps to (see
# market_reading_schema.VALID_MTF_KEYS). The bias surfaced for a reading is that
# of the timeframes ABOVE the requested one.
_MTF_LADDER = ["M15", "H1", "H4", "D1", "W1"]
_MTF_KEY = {"M15": "m15", "H1": "h1", "H4": "h4", "D1": "d1", "W1": "w1"}
DEFAULT_MTF_BIAS_LOOKBACK = 200


def build_cache_mtf_provider(
    candles_store: Any,
    lookback: int = DEFAULT_MTF_BIAS_LOOKBACK,
) -> Callable[[str, str], Mapping[str, Sequence[dict]]]:
    """Build an ``mtf_provider`` that reads the UPPER timeframes' candles straight
    from the candle CACHE — a pure read, NO Twelve Data call, NO new detection.

    Without this wired (the prior state), ``regime.mtf_confluence`` was always
    empty in live (no provider injected), so the multi-timeframe bias never
    surfaced. The returned callable maps each upper timeframe to its cached OHLC
    rows as plain dicts; ``candles_to_regime`` then derives the descriptive bias
    via the engine's existing trend logic. Timeframes with no cached candles are
    simply omitted (graceful — the panel degrades, never errors).
    """

    def _provider(instrument: str, timeframe: str) -> Mapping[str, Sequence[dict]]:
        tf = (timeframe or "").upper()
        if tf not in _MTF_LADDER:
            return {}
        out: dict[str, list[dict]] = {}
        for upper in _MTF_LADDER[_MTF_LADDER.index(tf) + 1:]:
            try:
                candles = candles_store.get_last_n_candles(instrument, upper, lookback)
            except Exception:  # pragma: no cover — defensive cache read
                continue
            if not candles:
                continue
            out[_MTF_KEY[upper]] = [
                {
                    "open": float(c.open),
                    "high": float(c.high),
                    "low": float(c.low),
                    "close": float(c.close),
                }
                for c in candles
            ]
        return out

    return _provider


__all__ = [
    "MarketReadingAssembler",
    "SmcPipelineFn",
    "build_cache_mtf_provider",
    "expected_last_candle_close",
]
