#!/usr/bin/env python
"""
DS-1 — generate the frozen design-gallery sample data from REAL product data.

Source: the live SQLite stores (data/market_readings.db, data/candles.db). These
hold the actual MarketReading payloads and OHLC windows the /app and /zones
surfaces render, so the mockups look like the product — nothing is invented.

The stored payloads are the LEGACY engine shape (bos/choch, touch_ats/touch_count,
description_source=haiku_generated|template_fallback). This script normalises them
to the CURRENT TypeScript contract (`@/types/market-reading`) with a strict
per-object whitelist:
  · rename  bos → current_bos, choch → current_choch
  · drop    legacy-only fields (_logic_version, touch_ats, touch_count)
  · omit    `contacts` (the VZ-1 ledger the legacy rows never carried — the type
            treats it as empty when absent; we do NOT fabricate contacts)
  · coerce  conditions.description_source → 'engine_template' (the type's single
            legal literal; provenance metadata only — the description TEXT is
            kept verbatim)
  · scrub   any event whose text carries the U+FFFD replacement char (an old
            encoding artefact) — the event is dropped, never patched

Every numeric market fact (prices, levels, zones, timestamps) is copied verbatim.

Usage:  python webapp/scripts/gen_ds_samples.py [--data-dir PATH] [--out-dir PATH]
"""
from __future__ import annotations
import argparse
import io
import json
import os
import re
import sqlite3
from datetime import datetime, timezone

REPL = "�"  # replacement char — marks legacy encoding corruption


def has_bad(text: object) -> bool:
    return isinstance(text, str) and REPL in text


# ── chart-bearing readings + their candle windows (instrument, tf, close_ts) ──
READINGS = [
    ("SAMPLE_READING_XAU_H4", "XAUUSD", "H4", "2026-07-31T20:00:00Z"),
    ("SAMPLE_READING_EUR_M15", "EURUSD", "M15", "2026-07-31T21:00:00Z"),
    ("SAMPLE_READING_XAU_D1", "XAUUSD", "D1", "2026-07-31T00:00:00Z"),
    ("SAMPLE_READING_XAU_M15_SPARSE", "XAUUSD", "M15", "2026-07-04T18:00:00Z"),
]
CANDLE_WINDOWS = [
    ("SAMPLE_CANDLES_XAU_H4", "XAUUSD", "H4", "2026-07-31T20:00:00Z", 260),
    ("SAMPLE_CANDLES_XAU_M15_SPARSE", "XAUUSD", "M15", "2026-07-04T18:00:00Z", 220),
]

HEADER = (
    "/**\n"
    " * DS-1 — Frozen sample data for the design gallery.\n"
    " *\n"
    " * REAL product data, copied from data/market_readings.db and data/candles.db\n"
    " * (the same payloads /app and /zones render live). NOT invented by hand.\n"
    " *\n"
    " * Generated by webapp/scripts/gen_ds_samples.py — do NOT edit by hand; re-run\n"
    " * the generator against the DB to refresh. Legacy payloads are normalised to\n"
    " * the current @/types/market-reading contract (see the script header for the\n"
    " * exact whitelist). No network, no secrets, no PII.\n"
    " */\n"
)


def pick(d: dict, keys: list[str]) -> dict:
    """Whitelist: keep only listed keys that are present (drops excess props)."""
    return {k: d[k] for k in keys if k in d and d[k] is not None}


def map_break(b: dict | None) -> dict | None:
    if not b:
        return None
    return pick(b, ["id", "direction", "level", "broken_at", "validation_status", "bars_ago"])


def map_ob(z: dict) -> dict:
    return pick(z, ["id", "direction", "level_high", "level_low", "importance", "status",
                    "created_at", "tested", "mitigated_at", "origin", "session", "user_flagged"])


def map_fvg(z: dict) -> dict:
    return pick(z, ["id", "direction", "level_high", "level_low", "status", "created_at",
                    "tested", "mitigated_at", "fill_level", "session", "user_flagged"])


def map_liq(z: dict) -> dict:
    return pick(z, ["id", "side", "kind", "level", "touches", "is_external", "status",
                    "created_at", "swept_at", "broken_at", "user_flagged"])


def map_structure(st: dict) -> dict:
    out: dict = {
        "current_bos": map_break(st.get("bos")),
        "current_choch": map_break(st.get("choch")),
        "order_blocks": [map_ob(z) for z in (st.get("order_blocks") or [])],
        "fair_value_gaps": [map_fvg(z) for z in (st.get("fair_value_gaps") or [])],
    }
    if st.get("bos_events"):
        out["bos_events"] = [map_break(b) for b in st["bos_events"]]
    if st.get("choch_events"):
        out["choch_events"] = [map_break(b) for b in st["choch_events"]]
    if st.get("liquidity_pools"):
        out["liquidity_pools"] = [map_liq(z) for z in st["liquidity_pools"]]
    if st.get("consumed_order_blocks"):
        out["consumed_order_blocks"] = [map_ob(z) for z in st["consumed_order_blocks"]]
    if st.get("consumed_fair_value_gaps"):
        out["consumed_fair_value_gaps"] = [map_fvg(z) for z in st["consumed_fair_value_gaps"]]
    if st.get("retest_in_progress"):
        out["retest_in_progress"] = pick(st["retest_in_progress"], ["level", "type", "started_at"])
    return out


def map_regime(reg: dict) -> dict:
    out = pick(reg, ["trend", "volatility_observed", "market_phase", "mtf_confluence"])
    if reg.get("volatility_detail"):
        out["volatility_detail"] = pick(reg["volatility_detail"],
            ["recent_avg", "baseline_avg", "ratio", "recent_n", "baseline_n", "threshold_low", "threshold_high"])
    if reg.get("trend_reference"):
        out["trend_reference"] = pick(reg["trend_reference"], ["kind", "direction", "level", "broken_at", "bars_ago"])
    return out


def map_events(ev: dict) -> dict:
    def clean_list(items, keys):
        out = []
        for it in items or []:
            if any(has_bad(v) for v in it.values()):
                continue  # drop legacy-corrupted event, never patch
            out.append(pick(it, keys))
        return out
    return {
        "news_upcoming": clean_list(ev.get("news_upcoming"),
            ["event", "scheduled_at", "time_to_event_min", "impact", "currency", "potential_effect_description", "event_id"]),
        "news_just_published": clean_list(ev.get("news_just_published"),
            ["event", "published_at", "actual", "forecast", "previous", "surprise_direction", "currency", "impact", "potential_effect_description", "event_id"]),
        "technical_triggers_recent": clean_list(ev.get("technical_triggers_recent"),
            ["type", "occurred_at", "minutes_ago"]),
    }


def map_reading(p: dict) -> dict:
    out: dict = {
        "schema_version": "2.0.0",
        "header": pick(p["header"], ["instrument", "timeframe", "candle_close_ts", "close_price", "analysis_window_bars"]),
        "structure": map_structure(p["structure"]),
        "regime": map_regime(p["regime"]),
        "events": map_events(p["events"]),
        "conditions": {
            "tags": p["conditions"].get("tags", []),
            "description": p["conditions"]["description"],
            "description_source": "engine_template",
        },
    }
    if p.get("market_status"):
        out["market_status"] = p["market_status"]
    if p.get("reference_levels"):
        out["reference_levels"] = pick(p["reference_levels"],
            ["day_open", "week_open", "prev_day_high", "prev_day_low", "prev_week_high", "prev_week_low", "day_complete", "week_complete"])
    # last honesty gate: the narrated description must be clean of corruption.
    if has_bad(out["conditions"]["description"]):
        raise SystemExit("selected reading has a corrupted description — pick another")
    return out


def iso_to_epoch(ts: str) -> int:
    return int(datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone(timezone.utc).timestamp())


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(here, "..", ".."))
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default=os.path.join(repo_root, "data"))
    ap.add_argument("--out-dir", default=os.path.join(here, "..", "lib", "ds-samples"))
    args = ap.parse_args()

    mr = sqlite3.connect(os.path.join(args.data_dir, "market_readings.db"))
    cc = sqlite3.connect(os.path.join(args.data_dir, "candles.db"))
    os.makedirs(args.out_dir, exist_ok=True)

    # readings.ts
    buf = io.StringIO()
    buf.write(HEADER)
    buf.write("import type { MarketReading } from '@/types/market-reading';\n\n")
    names = []
    for var, inst, tf, ts in READINGS:
        row = mr.execute(
            "SELECT payload_json FROM market_readings WHERE instrument=? AND timeframe=? AND candle_close_ts=?",
            (inst, tf, ts)).fetchone()
        if not row:
            raise SystemExit(f"missing reading {inst} {tf} {ts}")
        obj = map_reading(json.loads(row[0]))
        buf.write(f"export const {var}: MarketReading = {json.dumps(obj, ensure_ascii=False, indent=2)};\n\n")
        names.append(var)
    buf.write("export const SAMPLE_READINGS: readonly MarketReading[] = [\n")
    for n in names:
        buf.write(f"  {n},\n")
    buf.write("];\n")
    with open(os.path.join(args.out_dir, "readings.ts"), "w", encoding="utf-8", newline="\n") as f:
        f.write(buf.getvalue())
    print(f"wrote readings.ts ({len(names)} readings)")

    # candles.ts
    buf = io.StringIO()
    buf.write(HEADER)
    buf.write("import type { Candle } from '@/types/market-reading';\n\n")
    for var, inst, tf, end_ts, n in CANDLE_WINDOWS:
        rows = cc.execute(
            "SELECT ts,open,high,low,close,volume FROM candles_cache WHERE instrument=? AND timeframe=? AND ts<=? ORDER BY ts DESC LIMIT ?",
            (inst, tf, end_ts, n)).fetchall()
        rows = list(reversed(rows))
        buf.write(f"export const {var}: readonly Candle[] = [\n")
        for ts, o, h, l, cl, vol in rows:
            v = f", volume: {vol}" if vol is not None else ""
            buf.write(f"  {{ time: {iso_to_epoch(ts)}, open: {o}, high: {h}, low: {l}, close: {cl}{v} }},\n")
        buf.write("];\n\n")
        print(f"wrote {var} ({len(rows)} candles)")
    with open(os.path.join(args.out_dir, "candles.ts"), "w", encoding="utf-8", newline="\n") as f:
        f.write(buf.getvalue())
    print("wrote candles.ts")


if __name__ == "__main__":
    main()
