"""Legal endpoints: Terms of Service & Privacy Policy.

Public, unauthenticated, geo-block-bypassed. Required by:
  * Stripe / payment processors (T&C URL must be reachable).
  * RGPD Article 13 (information to data subjects).
  * UE Directive 2024/2811 finfluencers (duty to disclose status).

Multi-language: ``?lang=fr|en|de|es`` query param, or auto-detected
from ``Accept-Language``. Default = English.

Returns plain Markdown via ``text/markdown`` so the same content can
be rendered in a browser or piped into a marketing site.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import PlainTextResponse

from src.api.disclaimers import (
    DEFAULT_LANG,
    SUPPORTED_LANGS,
    detect_language_from_request,
)

router = APIRouter(tags=["legal"])

# 2026-07-05 : retrait du Québec des juridictions exclues (juridiction de
# rattachement de l'entreprise — décision fondateur, alignée sur le retrait de
# CA-QC du GeoBlockMiddleware). Bump = nouvel horodatage de consentement.
LAST_UPDATED = "2026-07-05"

# Canonical CGU document — rendered TEL QUEL by /api/v1/legal/conditions and the
# webapp /conditions page. Repo-root-relative (this file is src/api/routes/).
CONDITIONS_DOC_PATH = (
    Path(__file__).resolve().parents[3] / "docs" / "legal" / "conditions-utilisation.md"
)
# Version stamp for the canonical document. Kept in lockstep with the date in
# the markdown header and with the consent version recorded at registration.
CONDITIONS_VERSION = LAST_UPDATED


# ─── Terms of Service ─────────────────────────────────────────────────────

_TERMS: Dict[str, str] = {
    "en": f"""# Smart Sentinel AI — Terms of Service

_Last updated: {LAST_UPDATED}_

## 1. What this service is

Smart Sentinel AI publishes **algorithmic market analyses** (the
"Analyses") generated by deterministic confluence scoring and
optional large-language-model commentary. The Analyses are an
**information service**, not personalised investment advice.

## 2. Who we are not

Smart Sentinel AI is **not**:
- a registered investment adviser under the U.S. Investment Advisers
  Act of 1940 §202(a)(11);
- an authorised firm under the UK Financial Services and Markets Act
  2000 (FSMA);
- a conseiller en investissements financiers (CIF) under the AMF
  Règlement général;
- a Vermögensverwalter under §32 KWG.

We do not hold client funds and never execute trades on your behalf.

## 3. Restricted jurisdictions

The service is unavailable to natural or legal persons resident in:
United States, United Kingdom, and any country on the U.S. OFAC
Specially Designated Nationals (SDN) comprehensive sanctions list.
Access from those jurisdictions returns HTTP 451. The service is
operated from Quebec (Canada), where it is fully available.

## 4. Risk warning

Trading leveraged derivatives (CFDs, futures, FX, gold) is
high-risk. Between 74% and 89% of retail accounts lose money. Past
performance of an analysis is not indicative of future results. You
must not trade with money you cannot afford to lose.

## 5. Liability

To the maximum extent permitted by law, Smart Sentinel AI is not
liable for trading losses, missed opportunities, data inaccuracies,
or service interruptions. The service is provided "as-is" without
warranty of fitness for any particular purpose.

## 6. Acceptable use

You may not: redistribute the Analyses commercially, scrape the
service beyond your contractual rate limit, attempt to identify
proprietary signal logic by black-box probing, or use the service
to facilitate transactions for sanctioned persons.

## 7. Contact

Operator: Loukmane Bessam — loukmanebessam@gmail.com.
""",
    "fr": f"""# Smart Sentinel AI — Conditions Générales d'Utilisation

_Dernière mise à jour : {LAST_UPDATED}_

## 1. Nature du service

Smart Sentinel AI publie des **analyses algorithmiques de marché**
(les « Analyses ») générées par un moteur déterministe de
confluence, complétées par du commentaire LLM optionnel. Les
Analyses constituent un **service d'information**, pas un conseil
en investissement personnalisé.

## 2. Ce que nous ne sommes pas

Smart Sentinel AI **n'est pas** :
- un conseiller en investissements financiers (CIF) au sens du
  Règlement général de l'AMF ;
- une entreprise d'investissement agréée par l'ACPR ;
- une plateforme d'exécution d'ordres.

Nous ne détenons aucun fonds client et n'exécutons aucun ordre.

## 3. Juridictions exclues

Le service est indisponible aux personnes physiques ou morales
résidant aux États-Unis, au Royaume-Uni, ainsi que dans tout pays
figurant sur la liste OFAC SDN. L'accès depuis ces juridictions
renvoie un HTTP 451. Le service est exploité depuis le Québec
(Canada) et y est pleinement disponible.

## 4. Avertissement sur les risques

Le trading de produits dérivés à effet de levier (CFD, futures, FX,
or) est un investissement à haut risque. **74 % à 89 % des comptes
particuliers perdent de l'argent.** Les performances passées d'une
analyse ne préjugent pas des résultats futurs.

## 5. Responsabilité

Smart Sentinel AI ne saurait être tenue responsable de pertes de
trading, opportunités manquées, inexactitudes de données ou
interruptions de service. Le service est fourni « en l'état », sans
garantie d'adéquation à un objectif particulier.

## 6. Usage acceptable

Vous ne pouvez pas : redistribuer commercialement les Analyses,
scraper le service au-delà des limites contractuelles, effectuer du
reverse-engineering de la logique propriétaire, ou utiliser le
service pour faciliter des transactions de personnes sous sanctions.

## 7. Contact

Exploitant : Loukmane Bessam — loukmanebessam@gmail.com.
""",
    "de": f"""# Smart Sentinel AI — Nutzungsbedingungen

_Zuletzt aktualisiert: {LAST_UPDATED}_

## 1. Leistungsbeschreibung

Smart Sentinel AI veröffentlicht **algorithmische Marktanalysen**
(„Analysen"), erzeugt durch ein deterministisches Confluence-System
sowie optionalen LLM-Kommentar. Die Analysen sind ein
**Informationsdienst**, keine individuelle Anlageberatung.

## 2. Was wir nicht sind

Smart Sentinel AI ist **kein** zugelassenes Wertpapierdienstleistungs-
unternehmen nach §32 KWG, kein Anlageberater und kein Vermögens-
verwalter.

## 3. Ausgeschlossene Rechtsräume

Der Dienst ist in den USA, im Vereinigten Königreich und in allen
OFAC-SDN-sanktionierten Ländern nicht verfügbar. Zugriffe von dort
werden mit HTTP 451 abgewiesen. Der Dienst wird von Quebec (Kanada)
aus betrieben und ist dort uneingeschränkt verfügbar.

## 4. Risikohinweis

Der Handel mit gehebelten Derivaten (CFDs, Futures, FX, Gold) ist
hochriskant. **74-89% der Privatanleger verlieren Geld.** Frühere
Analyseergebnisse sind kein verlässlicher Indikator für die Zukunft.

## 5. Haftung

Smart Sentinel AI haftet nicht für Handelsverluste, entgangene
Gewinne, Datenungenauigkeiten oder Dienstunterbrechungen. Der Dienst
wird „wie besehen" bereitgestellt.

## 6. Akzeptable Nutzung

Untersagt sind: kommerzielle Weiterverbreitung, Scraping über
Vertragsgrenzen hinaus, Reverse Engineering der Signal-Logik und
Nutzung zur Umgehung von Sanktionen.

## 7. Kontakt

Betreiber: Loukmane Bessam — loukmanebessam@gmail.com.
""",
    "es": f"""# Smart Sentinel AI — Términos de Servicio

_Última actualización: {LAST_UPDATED}_

## 1. Naturaleza del servicio

Smart Sentinel AI publica **análisis algorítmicos de mercado** (los
«Análisis»), generados por un motor determinista de confluencia y
comentario LLM opcional. Los Análisis constituyen un **servicio de
información**, no asesoramiento de inversión personalizado.

## 2. Lo que no somos

Smart Sentinel AI **no** es una empresa de servicios de inversión
autorizada por la CNMV ni un asesor financiero registrado.

## 3. Jurisdicciones excluidas

El servicio no está disponible en Estados Unidos, Reino Unido ni en
países sancionados por OFAC SDN. El acceso desde esas jurisdicciones
devuelve HTTP 451. El servicio se opera desde Quebec (Canadá), donde
está plenamente disponible.

## 4. Advertencia de riesgo

Operar con derivados apalancados (CFD, futuros, FX, oro) es de alto
riesgo. **El 74-89% de las cuentas minoristas pierden dinero.** El
rendimiento pasado no garantiza resultados futuros.

## 5. Responsabilidad

Smart Sentinel AI no se hace responsable de pérdidas, oportunidades
perdidas, inexactitudes de datos o interrupciones del servicio. El
servicio se ofrece «tal cual», sin garantía de idoneidad.

## 6. Uso aceptable

Está prohibido: redistribución comercial, scraping fuera de los
límites del contrato, ingeniería inversa de la lógica propietaria y
uso para facilitar transacciones de personas sancionadas.

## 7. Contacto

Operador: Loukmane Bessam — loukmanebessam@gmail.com.
""",
}


_PRIVACY: Dict[str, str] = {
    "en": f"""# Smart Sentinel AI — Privacy Policy

_Last updated: {LAST_UPDATED}_

## 1. Data controller

Loukmane Bessam (sole operator). Contact: loukmanebessam@gmail.com.

## 2. Personal data we process

| Data | Lawful basis (RGPD Art. 6) | Retention |
|------|----------------------------|-----------|
| Email address | Contract performance | Account lifetime + 3 yrs |
| API key hash | Contract performance | Account lifetime |
| IP address & country code | Legitimate interest (security, geo-blocking) | 30 days |
| Telegram chat ID | Contract performance | Account lifetime |
| Stripe customer ID | Legal obligation (accounting) | 10 yrs |
| Webhook delivery logs | Legitimate interest (debugging) | 14 days |

We do **not** collect: real name, address, payment-card number
(Stripe handles this), browsing history, or trading account state.

## 3. Sub-processors

* **Anthropic, Inc.** (US) — LLM inference for narratives. Data
  shared: signal payload (no PII). Standard Contractual Clauses
  2021/914/EU in place.
* **Stripe, Inc.** (US/IE) — payment processing. Data shared: email,
  Stripe customer ID. SCCs in place.
* **Telegram FZ-LLC** (UAE) — message delivery. Data shared: chat ID
  and message body.
* **Hosting provider** — Railway / Fly.io (depending on deployment).

## 4. Your rights (RGPD Art. 15-22)

You may at any time request: access to your data, rectification,
erasure ("right to be forgotten"), portability (machine-readable
export), restriction of processing, or objection. Send any request
to loukmanebessam@gmail.com — we have 30 days to respond.

## 5. Complaints

You may lodge a complaint with your national data-protection
authority. In France: CNIL — www.cnil.fr.

## 6. Cookies

The Smart Sentinel AI API itself sets no cookies. The marketing
website may use first-party analytics cookies; consent is collected
via a banner before any non-essential cookie is set.
""",
    "fr": f"""# Smart Sentinel AI — Politique de confidentialité

_Dernière mise à jour : {LAST_UPDATED}_

## 1. Responsable de traitement

Loukmane Bessam (exploitant unique). Contact : loukmanebessam@gmail.com.

## 2. Données personnelles traitées

| Donnée | Base légale (RGPD Art. 6) | Durée |
|--------|---------------------------|-------|
| Adresse e-mail | Exécution du contrat | Durée du compte + 3 ans |
| Hash de clé API | Exécution du contrat | Durée du compte |
| Adresse IP et pays | Intérêt légitime (sécurité, geo-block) | 30 jours |
| ID Telegram | Exécution du contrat | Durée du compte |
| ID client Stripe | Obligation légale (comptabilité) | 10 ans |
| Logs de webhooks | Intérêt légitime (débogage) | 14 jours |

Nous **ne collectons pas** : nom, adresse postale, numéro de carte
bancaire (Stripe s'en charge), historique de navigation, état du
compte de trading.

## 3. Sous-traitants

* **Anthropic, Inc.** (US) — inférence LLM. Données : payload
  signal (pas de DCP). Clauses Contractuelles Types 2021/914/UE.
* **Stripe, Inc.** (US/IE) — paiement. Données : e-mail, ID Stripe.
  CCT en place.
* **Telegram FZ-LLC** (EAU) — livraison des messages.
* **Hébergeur** — Railway / Fly.io selon le déploiement.

## 4. Vos droits (RGPD Art. 15-22)

Vous pouvez à tout moment exercer vos droits d'accès, de
rectification, d'effacement, de portabilité, de limitation et
d'opposition. Toute demande à loukmanebessam@gmail.com — réponse
sous 30 jours.

## 5. Réclamations

Vous pouvez déposer une réclamation auprès de la CNIL — www.cnil.fr.

## 6. Cookies

L'API Smart Sentinel AI ne pose aucun cookie. Le site marketing
peut utiliser des cookies analytiques de première partie, soumis à
consentement explicite.
""",
    "de": f"""# Smart Sentinel AI — Datenschutzerklärung

_Zuletzt aktualisiert: {LAST_UPDATED}_

## 1. Verantwortlicher

Loukmane Bessam — loukmanebessam@gmail.com.

## 2. Verarbeitete personenbezogene Daten

| Datum | Rechtsgrundlage (DSGVO Art. 6) | Speicherdauer |
|-------|--------------------------------|---------------|
| E-Mail | Vertragserfüllung | Kontolaufzeit + 3 J. |
| API-Key-Hash | Vertragserfüllung | Kontolaufzeit |
| IP & Länderkennung | Berechtigtes Interesse | 30 Tage |
| Telegram-Chat-ID | Vertragserfüllung | Kontolaufzeit |
| Stripe-Kunden-ID | Rechtliche Verpflichtung | 10 Jahre |
| Webhook-Logs | Berechtigtes Interesse | 14 Tage |

## 3. Auftragsverarbeiter

Anthropic (USA), Stripe (USA/IE), Telegram (VAE), Hoster (Railway/
Fly.io). SCCs (2021/914/EU) sind abgeschlossen.

## 4. Ihre Rechte (DSGVO Art. 15-22)

Auskunft, Berichtigung, Löschung, Datenübertragbarkeit,
Einschränkung, Widerspruch. Anfragen an loukmanebessam@gmail.com.

## 5. Beschwerden

Zuständige Aufsichtsbehörde in Deutschland: BfDI — www.bfdi.bund.de.
""",
    "es": f"""# Smart Sentinel AI — Política de Privacidad

_Última actualización: {LAST_UPDATED}_

## 1. Responsable del tratamiento

Loukmane Bessam — loukmanebessam@gmail.com.

## 2. Datos personales tratados

| Dato | Base legal (RGPD Art. 6) | Conservación |
|------|--------------------------|--------------|
| Correo electrónico | Ejecución del contrato | Vida de la cuenta + 3 años |
| Hash de clave API | Ejecución del contrato | Vida de la cuenta |
| IP y país | Interés legítimo (seguridad) | 30 días |
| ID de Telegram | Ejecución del contrato | Vida de la cuenta |
| ID cliente Stripe | Obligación legal | 10 años |
| Logs de webhooks | Interés legítimo | 14 días |

## 3. Encargados del tratamiento

Anthropic (EE.UU.), Stripe (EE.UU./IE), Telegram (EAU), proveedor de
hosting (Railway/Fly.io). CCTs 2021/914/UE en vigor.

## 4. Sus derechos (RGPD Art. 15-22)

Acceso, rectificación, supresión, portabilidad, limitación y
oposición. Solicitudes a loukmanebessam@gmail.com.

## 5. Reclamaciones

Autoridad de control: AEPD — www.aepd.es.
""",
}


def _resolve_lang(query_lang: Optional[str], request: Request) -> str:
    if query_lang:
        code = query_lang.strip().lower()[:2]
        if code in SUPPORTED_LANGS:
            return code
    return detect_language_from_request(dict(request.headers))


@router.get("/api/v1/terms", response_class=PlainTextResponse)
async def terms_of_service(
    request: Request,
    lang: Optional[str] = Query(None, description="Language: fr, en, de, es"),
):
    """Public Terms of Service. No authentication required."""
    code = _resolve_lang(lang, request)
    body = _TERMS.get(code, _TERMS[DEFAULT_LANG])
    return PlainTextResponse(
        body,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Language": code, "Cache-Control": "public, max-age=3600"},
    )


@router.get("/api/v1/privacy", response_class=PlainTextResponse)
async def privacy_policy(
    request: Request,
    lang: Optional[str] = Query(None, description="Language: fr, en, de, es"),
):
    """Public Privacy Policy. No authentication required."""
    code = _resolve_lang(lang, request)
    body = _PRIVACY.get(code, _PRIVACY[DEFAULT_LANG])
    return PlainTextResponse(
        body,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Language": code, "Cache-Control": "public, max-age=3600"},
    )


@router.get("/api/v1/legal/version")
async def legal_version():
    """Machine-readable version stamp for clients to detect T&C updates."""
    return {
        "terms_version": LAST_UPDATED,
        "privacy_version": LAST_UPDATED,
        "conditions_version": CONDITIONS_VERSION,
        "supported_languages": list(SUPPORTED_LANGS),
        "fetched_at": datetime.now(timezone.utc).isoformat(),
    }


def _read_conditions_doc() -> str:
    """Read the canonical CGU markdown verbatim. 503 if the file is missing."""
    try:
        return CONDITIONS_DOC_PATH.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail="Conditions document unavailable",
        ) from exc


@router.get("/api/v1/legal/conditions", response_class=PlainTextResponse)
async def conditions_document():
    """Serve ``docs/legal/conditions-utilisation.md`` TEL QUEL (verbatim).

    The webapp ``/conditions`` page fetches this through the same-origin
    ``/api/*`` rewrite and renders the markdown without rewriting the text.
    """
    body = _read_conditions_doc()
    return PlainTextResponse(
        body,
        media_type="text/markdown; charset=utf-8",
        headers={
            "Content-Language": "fr",
            "X-Document-Version": CONDITIONS_VERSION,
            "Cache-Control": "public, max-age=3600",
        },
    )


@router.get("/api/v1/legal/conditions/meta")
async def conditions_meta():
    """Version + date for the canonical CGU document (machine-readable)."""
    return {
        "version": CONDITIONS_VERSION,
        "last_updated": LAST_UPDATED,
        "fetched_at": datetime.now(timezone.utc).isoformat(),
    }
