import createMiddleware from 'next-intl/middleware';
import { NextRequest, NextResponse } from 'next/server';
import { DEFAULT_LOCALE, SUPPORTED_LOCALES } from './i18n';

// V1 ships FR only. EN/DE/ES translation files stay in the repo as dormant
// infrastructure but their routes must NOT be indexable — empty/stub locale
// pages would trigger SEO duplication penalties. Any incoming /en/* /de/* /es/*
// request is 302-redirected to the FR equivalent (default locale, served
// without prefix thanks to `localePrefix: 'as-needed'`).
const INACTIVE_LOCALES = ['en', 'de', 'es'] as const;

// Closed private beta: when BETA_LOCKDOWN is on, the product surfaces are only
// reachable by a logged-in account. This edge guard is the FAST first layer —
// a request without the session cookie is redirected to /connexion before the
// page renders. It is defence-in-depth, NOT the source of truth: the backend
// (BetaAuthMiddleware) 401s every product API call regardless, and the cookie's
// VALIDITY is verified there. A stale/forged cookie still gets nothing from the
// API; here we only check presence to avoid a pointless render.
const BETA_LOCKDOWN =
  process.env.BETA_LOCKDOWN === '1' || process.env.BETA_LOCKDOWN === 'true';
const SESSION_COOKIE = 'mia_session';
// Product routes behind the login wall (FR is prefixless; en/de/es are stripped
// to FR by the guard below before this check runs).
const PROTECTED_PREFIXES = ['/app', '/zones', '/scanner', '/compte', '/abonnement'];

function isProtectedPath(pathname: string): boolean {
  return PROTECTED_PREFIXES.some(
    (p) => pathname === p || pathname.startsWith(`${p}/`),
  );
}

const intlMiddleware = createMiddleware({
  locales: SUPPORTED_LOCALES,
  defaultLocale: DEFAULT_LOCALE,
  localePrefix: 'as-needed',
  // Locale detection MUST stay off. With it on, a browser advertising
  // `Accept-Language: en` makes next-intl 302 `/` → `/en` (en is a supported
  // but INACTIVE locale); the redirect above then strips `/en` → `/`, which
  // next-intl re-detects as `en` → `/en` … = an infinite redirect loop
  // (ERR_TOO_MANY_REDIRECTS) for every en/de/es visitor. V1 ships FR only, so
  // `/` always serves the default locale; direct /en/* visits are still
  // 302-redirected to FR by the guard above.
  localeDetection: false,
});

export default function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  for (const inactive of INACTIVE_LOCALES) {
    if (pathname === `/${inactive}` || pathname.startsWith(`/${inactive}/`)) {
      const stripped = pathname.slice(inactive.length + 1) || '/';
      const target = request.nextUrl.clone();
      target.pathname = stripped;
      return NextResponse.redirect(target, 302);
    }
  }

  // Closed-beta login wall (edge layer). Cookieless visitors to a product route
  // are bounced to the login page with a ?next= return path.
  if (BETA_LOCKDOWN && isProtectedPath(pathname)) {
    const hasSession = request.cookies.has(SESSION_COOKIE);
    if (!hasSession) {
      const target = request.nextUrl.clone();
      target.pathname = '/connexion';
      target.search = '';
      target.searchParams.set('next', pathname);
      return NextResponse.redirect(target, 307);
    }
  }

  return intlMiddleware(request);
}

export const config = {
  // Skip API routes, Next internals, Vercel internals, file requests with
  // an extension (favicon.ico, *.svg, *.png …), and the metadata routes
  // generated by Next 15 (icon.tsx, apple-icon.tsx). Without these last
  // exclusions the next-intl matcher treats `/icon` as a locale segment
  // and 404s the generated PNG.
  matcher: ['/((?!api|_next|_vercel|icon|apple-icon|opengraph-image|.*\\..*).*)'],
};
