import createMiddleware from 'next-intl/middleware';
import { NextRequest, NextResponse } from 'next/server';
import { DEFAULT_LOCALE, SUPPORTED_LOCALES } from './i18n';

// All locales in SUPPORTED_LOCALES are now ACTIVE (fr/en/de/es/it/pt/nl/pl/ar).
// The former en/de/es → fr redirect guard is gone: every locale serves real,
// translated content, so there is nothing to redirect away from and no
// SEO-duplication risk.
//
// `localeDetection: true` — an incoming request with no locale prefix and no
// NEXT_LOCALE cookie is matched against `Accept-Language`. A browser set to
// Arabic lands on /ar, a German browser on /de, everyone else on the default
// (FR) served prefix-less thanks to `localePrefix: 'as-needed'`. The language
// switcher writes the NEXT_LOCALE cookie, so an explicit choice always wins
// over the browser header on subsequent visits.
const intlMiddleware = createMiddleware({
  locales: SUPPORTED_LOCALES,
  defaultLocale: DEFAULT_LOCALE,
  localePrefix: 'as-needed',
  localeDetection: true,
});

// Closed private beta: when BETA_LOCKDOWN is on, the product surfaces are only
// reachable by a logged-in account. This edge guard is the FAST first layer —
// a request without the session cookie is redirected to /connexion before the
// page renders. It is defence-in-depth, NOT the source of truth: the backend
// (BetaAuthMiddleware) 401s every product API call regardless, and the cookie's
// VALIDITY is verified there. A stale/forged cookie still gets nothing from the
// API; here we only check presence to avoid a pointless render.
const BETA_LOCKDOWN =
  process.env.BETA_LOCKDOWN === '1' || process.env.BETA_LOCKDOWN === 'true';
const SESSION_COOKIE = 'mia_session';
// Product routes behind the login wall. FR is prefixless; a leading locale
// segment (/en/app …) is stripped before the check so all locales are gated.
const PROTECTED_PREFIXES = ['/app', '/zones', '/scanner', '/compte', '/abonnement'];

function stripLocale(pathname: string): string {
  const segs = pathname.split('/').filter(Boolean);
  const first = segs[0] as (typeof SUPPORTED_LOCALES)[number] | undefined;
  if (first && SUPPORTED_LOCALES.includes(first)) {
    return '/' + segs.slice(1).join('/');
  }
  return pathname;
}

function isProtectedPath(pathname: string): boolean {
  const p = stripLocale(pathname);
  return PROTECTED_PREFIXES.some(
    (prefix) => p === prefix || p.startsWith(`${prefix}/`),
  );
}

export default function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Closed-beta login wall (edge layer). Cookieless visitors to a product route
  // are bounced to the login page with a ?next= return path.
  if (BETA_LOCKDOWN && isProtectedPath(pathname)) {
    const hasSession = request.cookies.has(SESSION_COOKIE);
    if (!hasSession) {
      const target = request.nextUrl.clone();
      target.pathname = '/connexion';
      target.search = '';
      target.searchParams.set('next', pathname);
      return NextResponse.redirect(target, 307);
    }
  }

  return intlMiddleware(request);
}

export const config = {
  // Skip API routes, Next internals, Vercel internals, file requests with
  // an extension (favicon.ico, *.svg, *.png …), and the metadata routes
  // generated by Next 15 (icon.tsx, apple-icon.tsx). Without these last
  // exclusions the next-intl matcher treats `/icon` as a locale segment
  // and 404s the generated PNG.
  matcher: ['/((?!api|_next|_vercel|icon|apple-icon|opengraph-image|.*\\..*).*)'],
};
